## Basic Level (1–20)

#### **1. What is pandas?**
Pandas is an open-source Python library designed for high-performance data manipulation, analysis, and cleaning. Built on top of the NumPy library, it acts as the backbone for most data science and machine learning workflows in Python.

**Core Data Structures**

* **Series:** A one-dimensional labeled array capable of holding any data type (integer, string, float, python objects, etc.). Think of it as a single column in a table.
* **DataFrame:** A two-dimensional, size-mutable, tabular data structure with labeled axes (rows and columns). It is the primary pandas object and functions like a highly powered Excel spreadsheet or SQL table.

**Why It Is Essential**

* **I/O Operations:** It seamlessly reads and writes data from multiple formats, including CSV, Excel, SQL databases, Parquet, and JSON.
* **Data Cleaning:** It provides built-in methods for handling missing data (`NaN`), dropping duplicates, and standardizing data types.
* **Data Transformation:** It allows for effortless slicing, filtering, reshaping, aggregating (groupby), and merging of disparate datasets.
* **Time Series Analysis:** It includes native tools for date range generation, frequency conversion, and moving window statistics.

In [1]:
# Importing Pandas in Python
import pandas as pd

#### **2. Why is Pandas used in Data Science?**
Pandas bridges the gap between raw, unstructured data and the clean datasets required for training machine learning models. It streamlines the exploratory data analysis and feature engineering steps that typically consume the majority of a data science workflow.

* **Ecosystem Integration:** Acts as the central data hub, seamlessly passing structured matrices to Scikit-learn, TensorFlow, or PyTorch, and feeding visual libraries like Matplotlib and Seaborn.
* **Vectorized Performance:** Built on a C backend, it replaces slow Python `for` loops with optimized, vectorized operations for rapid data transformations and mathematical calculations.
* **Heterogeneous Data:** Unlike strict numerical arrays, DataFrames effortlessly manage combinations of integers, floats, categorical strings, and time-series data in a single table.
* **Complex Aggregations:** Simplifies SQL-like operations—such as multi-level `groupby` aggregations, joins, and pivot tables—allowing you to extract analytical insights with minimal code.
* **Automated Alignment:** Automatically aligns data by label during arithmetic operations and merges, preventing critical index-mismatch errors when combining different datasets.
* **Handling Incompleteness:** Provides native, highly flexible methods to detect, drop, or impute missing values (`NaN`), which is crucial for real-world datasets before they reach an algorithm.

#### **3. What are the main data structures in Pandas?**
Pandas relies on two foundational data structures: the **Series** (1-dimensional) and the **DataFrame** (2-dimensional). Every operation in Pandas is essentially manipulating one or both of these structures.

**1. Series (1-Dimensional)**
A Series is a one-dimensional array-like object capable of holding any single data type (integers, strings, floats, objects). It consists of two main components: the actual data array and an associated array of data labels, called its *index*.

**2. DataFrame (2-Dimensional)**
A DataFrame is a two-dimensional, size-mutable tabular structure with rows and columns. You can think of it as a dictionary of aligned Series objects that all share the same index. This is the most commonly used pandas object.

**Core Differences**  
| Feature | Series | DataFrame |
| --- | --- | --- |
| **Dimensions** | 1D (Array/List-like) | 2D (Table/Grid-like) |
| **Data Types** | Homogeneous (single data type per Series) | Heterogeneous (each column can be a different data type) |
| **Structure** | Single column of data with an Index | Multiple columns of data, sharing a single Index |
| **Size Mutability** | Fixed size (adding elements requires recreating) | Mutable (easily add or drop rows/columns) |

In [2]:
import pandas as pd

# Creating a Series from a list with a custom string index
pm25_values = pd.Series(
    [45.2, 112.5, 89.0], 
    index=['Morning', 'Afternoon', 'Evening'], 
    name='PM2.5_Levels'
)

print(pm25_values)
print("\nAccessing by index label:", pm25_values['Afternoon'])

Morning       45.2
Afternoon    112.5
Evening       89.0
Name: PM2.5_Levels, dtype: float64

Accessing by index label: 112.5

In [3]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Date': ['2026-09-10', '2026-09-11', '2026-09-12'],
    'Station': ['Zone A', 'Zone B', 'Zone A'],
    'AQI': [85, 142, 90],
    'Status': ['Good', 'Poor', 'Satisfactory']
}

df = pd.DataFrame(data)

# Setting a specific column as the row index
df.set_index('Date', inplace=True)

display(df)

# Extracting a single column returns a Series
print("\nType of a single column:", type(df['AQI']))

           Station  AQI        Status
Date
2026-09-10  Zone A   85          Good
2026-09-11  Zone B  142          Poor
2026-09-12  Zone A   90  Satisfactory

Type of a single column: <class 'pandas.core.series.Series'>

#### **4. What is a Series?**
A **Series** is a one-dimensional, labeled array capable of holding any data type (integers, strings, floating-point numbers, Python objects). Think of it as a single column in a spreadsheet, where every row has a specific, immutable label.

**Key Characteristics**
* **The Index:** Unlike a standard Python list, every element in a Series has an explicit, customizable label (the index). If you don't provide one, Pandas assigns a default sequence (`0, 1, 2...`).
* **Data Homogeneity:** While it *can* hold mixed types (which forces the overall type to `object`), a Series is highly optimized when holding a single data type, allowing for memory efficiency and high-speed calculations.
* **Dual Behavior:** A Series acts like a hybrid between a Python dictionary (key-value pairs via the index) and a NumPy array (vectorized math operations).

In [4]:
import pandas as pd

# 1. Creating a Series from a standard list (receives a default integer index)
cities = pd.Series(['Bengaluru', 'Kolkata', 'Chennai', 'Mumbai'])
print("Default Index Series:\n", cities)

# 2. Creating a Series from a dictionary (dictionary keys automatically become the index)
air_quality_dict = {'Indiranagar': 85, 'HSR Layout': 142, 'Koramangala': 110}
aqi_series = pd.Series(air_quality_dict, name='AQI_Readings')
print("\nDictionary to Series:\n", aqi_series)

# 3. Accessing elements (Dictionary-like behavior)
print("\nAQI in HSR Layout:", aqi_series['HSR Layout'])

# 4. Vectorized Math (NumPy-like behavior)
# Adjusting every value simultaneously without writing a 'for' loop
adjusted_aqi = aqi_series + 10
print("\nAdjusted AQI (+10):\n", adjusted_aqi)

# 5. Boolean Filtering
# Selecting only the items that meet a specific condition
high_pollution = aqi_series[aqi_series > 100]
print("\nLocations with AQI > 100:\n", high_pollution)

Default Index Series:
 0    Bengaluru
1      Kolkata
2      Chennai
3       Mumbai
dtype: object

Dictionary to Series:
 Indiranagar     85
HSR Layout     142
Koramangala    110
Name: AQI_Readings, dtype: int64

AQI in HSR Layout: 142

Adjusted AQI (+10):
 Indiranagar     95
HSR Layout     152
Koramangala    120
Name: AQI_Readings, dtype: int64

Locations with AQI > 100:
 HSR Layout     142
Koramangala    110
Name: AQI_Readings, dtype: int64

#### **5. What is a DataFrame?**
A **DataFrame** is a two-dimensional, tabular data structure composed of rows and columns, functioning much like a SQL table or an Excel spreadsheet. Under the hood, it is essentially a dictionary of Pandas Series objects that all share the exact same row index.

**Key Characteristics**
* **Heterogeneous Types:** Unlike standard NumPy matrices, each column in a DataFrame can hold a entirely different data type (e.g., a string column next to a float column).
* **Labeled Axes:** Both rows (the index) and columns have explicit labels, allowing for intuitive data alignment, merging, and retrieval.
* **Size-Mutable:** You can dynamically append rows or insert/delete columns without needing to recreate the entire object.

In [5]:
import pandas as pd

# 1. Creating a DataFrame from a dictionary of lists (most common method)
# Each key becomes a column name, and each list becomes the column's data
data = {
    'City': ['Kolkata', 'Bengaluru', 'Chennai'],
    'PM10_Level': [102.4, 89.1, 76.5],
    'Status': ['Moderate', 'Satisfactory', 'Satisfactory']
}
df = pd.DataFrame(data)

print("Standard DataFrame:\n")
display(df)

# 2. Accessing components
# Extracting a single column returns a Series
pm10_series = df['PM10_Level']

# Extracting multiple columns returns a smaller DataFrame
subset_df = df[['City', 'Status']]

# 3. Adding a new column
# You can broadcast a single value or assign a calculated array/list
df['Country'] = 'India'
df['Requires_Action'] = df['PM10_Level'] > 100

print("\nDataFrame after adding columns:\n")
display(df)

# 4. Exploring the underlying structure
print("\nDataFrame Index:", df.index)
print("DataFrame Columns:", df.columns)
print("DataFrame Shape (Rows, Columns):", df.shape)

Standard DataFrame:

        City  PM10_Level        Status
0    Kolkata       102.4      Moderate
1  Bengaluru        89.1  Satisfactory
2    Chennai        76.5  Satisfactory

DataFrame after adding columns:

        City  PM10_Level        Status Country  Requires_Action
0    Kolkata       102.4      Moderate   India             True
1  Bengaluru        89.1  Satisfactory   India            False
2    Chennai        76.5  Satisfactory   India            False

DataFrame Index: RangeIndex(start=0, stop=3, step=1)
DataFrame Columns: Index(['City', 'PM10_Level', 'Status', 'Country', 'Requires_Action'], dtype='object')
DataFrame Shape (Rows, Columns): (3, 5)

#### **6. What is the difference between a Series and a DataFrame?**
The fundamental difference lies in dimensionality: a Series represents a single column of data (1D), whereas a DataFrame is a multi-column table (2D) composed of multiple aligned Series. Every column you extract from a DataFrame is returned as a Series.

**Key Structural Differences**

| Feature | `pd.Series` | `pd.DataFrame` |
| --- | --- | --- |
| **Dimensions** | 1-Dimensional (Array/List-like) | 2-Dimensional (Table/Grid-like) |
| **Data Types** | Homogeneous (typically a single data type) | Heterogeneous (each column can be a different type) |
| **Conceptual Model** | A single column of data with row labels (index) | A dictionary of Series objects sharing the exact same index |
| **Size Mutability** | Fixed size (adding elements usually requires recreating the object) | Mutable (add or drop columns and rows dynamically) |

In [6]:
import pandas as pd

# 1. Start with a DataFrame (2D)
data = {
    'Station': ['Indiranagar', 'BTM Layout', 'HSR Layout'],
    'PM25_Level': [45.2, 112.5, 89.0]
}
df = pd.DataFrame(data)
print("Original Object Type:", type(df))

# 2. Extracting a single column returns a Series (1D)
pm25_series = df['PM25_Level']
print("\nExtracted Column Type:", type(pm25_series))

# 3. Creating an independent Series
# If you don't specify an index, it defaults to 0, 1, 2... matching the DataFrame
aqi_status = pd.Series(['Good', 'Poor', 'Moderate'], name='Status')
print("\nIndependent Series:\n", aqi_status)

# 4. Combining them: Adding the Series as a new column in the DataFrame
df['AQI_Status'] = aqi_status
print("\nCombined DataFrame:\n")
display(df)

Original Object Type: <class 'pandas.core.frame.DataFrame'>

Extracted Column Type: <class 'pandas.core.series.Series'>

Independent Series:
 0        Good
1        Poor
2    Moderate
Name: Status, dtype: object

Combined DataFrame:

       Station  PM25_Level AQI_Status
0  Indiranagar        45.2       Good
1   BTM Layout       112.5       Poor
2   HSR Layout        89.0   Moderate

#### **7. How do you create a Series?**
You can create a Pandas Series by passing various Python or NumPy data structures into the `pd.Series()` constructor. The constructor accepts the data itself, an optional custom index, and an optional name for the Series.

**Common Data Sources for a Series**
* **Python Lists:** Automatically assigned a numeric index (0, 1, 2...) unless a custom index is provided.
* **Python Dictionaries:** The dictionary keys automatically become the Series index, and the values become the data.
* **NumPy Arrays:** Functions exactly like a list, leveraging NumPy's memory efficiency.
* **Scalar Values:** A single value (like an integer or string) that gets repeated across a provided index.

In [7]:
import pandas as pd
import numpy as np

# 1. Creating from a standard list (default integer index)
kit_sizes = pd.Series(['S', 'S', 'S', 'S'], name='Kit_Size')
print("From List (Default Index):\n", kit_sizes)

# 2. Creating from a list with a custom index
# The length of the index list must exactly match the length of the data list
squad_numbers = pd.Series(
    [10, 11, 10, 11], 
    index=['Messi', 'Raphinha', 'Mac Allister', 'Di Maria'],
    name='Squad_Number'
)
print("\nFrom List (Custom Index):\n", squad_numbers)

# 3. Creating from a Dictionary
# Pandas automatically uses the dictionary keys as the index labels
player_teams = {
    'Messi': 'Argentina',
    'Raphinha': 'FC Barcelona',
    'Mac Allister': 'Liverpool',
    'Di Maria': 'Argentina'
}
team_series = pd.Series(player_teams, name='Team')
print("\nFrom Dictionary:\n", team_series)

# 4. Creating from a NumPy array
# Useful when pulling data generated by mathematical functions
random_data = np.array([4.5, 8.2, 9.1])
np_series = pd.Series(random_data, index=['x', 'y', 'z'])
print("\nFrom NumPy Array:\n", np_series)

# 5. Creating from a Scalar value
# The single value 'Economy' is broadcasted across all provided index labels
flight_class = pd.Series('Economy', index=['Flight_1', 'Flight_2', 'Flight_3'])
print("\nFrom Scalar Value:\n", flight_class)

From List (Default Index):
 0    S
1    S
2    S
3    S
Name: Kit_Size, dtype: object

From List (Custom Index):
 Messi           10
Raphinha        11
Mac Allister    10
Di Maria        11
Name: Squad_Number, dtype: int64

From Dictionary:
 Messi              Argentina
Raphinha        FC Barcelona
Mac Allister       Liverpool
Di Maria           Argentina
Name: Team, dtype: object

From NumPy Array:
 x    4.5
y    8.2
z    9.1
dtype: float64

From Scalar Value:
 Flight_1    Economy
Flight_2    Economy
Flight_3    Economy
dtype: object

#### **8. How do you create a DataFrame?**
You can construct a DataFrame from scratch using several native Python data structures, though the most common approach is using a dictionary of lists. The `pd.DataFrame()` constructor automatically aligns the provided data into rows and columns.

**Common Data Sources for a DataFrame**
* **Dictionary of Lists:** Column-oriented creation where keys become column headers and lists become the column data.
* **List of Dictionaries:** Row-oriented creation where each dictionary represents a single row (useful when parsing JSON data).
* **2D NumPy Arrays:** Converts mathematical matrices into labeled tables by explicitly providing column and index names.
* **External Files:** In practice, you will most often create DataFrames by reading files using functions like `pd.read_csv()` or `pd.read_excel()`.

In [8]:
import pandas as pd
import numpy as np

# 1. From a Dictionary of Lists (Column-oriented)
# All lists must be the exact same length.
dict_data = {
    'City': ['Bengaluru', 'Kolkata', 'Chennai'],
    'AQI': [85, 102, 76],
    'Status': ['Satisfactory', 'Moderate', 'Satisfactory']
}
df_from_dict = pd.DataFrame(dict_data)
print("From Dictionary of Lists:\n")
display(df_from_dict)

# 2. From a List of Dictionaries (Row-oriented)
# Missing keys in specific dictionaries will automatically become NaN values.
list_data = [
    {'City': 'Bengaluru', 'AQI': 85},
    {'City': 'Kolkata', 'AQI': 102, 'Status': 'Moderate'},
    {'City': 'Chennai', 'AQI': 76, 'Status': 'Satisfactory'}
]
df_from_list = pd.DataFrame(list_data)
print("\nFrom List of Dictionaries:\n")
display(df_from_list)

# 3. From a 2D NumPy Array
# You must explicitly define the column names and index labels, otherwise they default to 0, 1, 2...
numpy_matrix = np.array([
    [85, 45.2], 
    [102, 55.1], 
    [76, 30.5]
])
df_from_numpy = pd.DataFrame(
    numpy_matrix, 
    columns=['AQI', 'PM2.5'], 
    index=['Bengaluru', 'Kolkata', 'Chennai']
)
print("\nFrom 2D NumPy Array:\n")
display(df_from_numpy)

From Dictionary of Lists:

        City  AQI        Status
0  Bengaluru   85  Satisfactory
1    Kolkata  102      Moderate
2    Chennai   76  Satisfactory

From List of Dictionaries:

        City  AQI        Status
0  Bengaluru   85           NaN
1    Kolkata  102      Moderate
2    Chennai   76  Satisfactory

From 2D NumPy Array:

             AQI  PM2.5
Bengaluru   85.0   45.2
Kolkata    102.0   55.1
Chennai     76.0   30.5

#### **9. How do you read data from a CSV file?**
The `pd.read_csv()` function is the workhorse for data ingestion in Pandas. It reads comma-separated values and converts them directly into a DataFrame, offering dozens of parameters to handle dates, specific columns, and missing values on the fly.

*(Note: You would need a local file named `customers.csv` to execute these exact commands).*

In [9]:
import pandas as pd

path = "./../Datasets/"
# 1. Basic Import
# Reads the entire file, assuming the first row contains column headers
df = pd.read_csv(path + 'customers.csv')
display(df.head())

# 2. Reading Specific Columns
# 'usecols' saves memory by only loading the columns you actually need for your analysis
df_subset = pd.read_csv(
    path + 'customers.csv', 
    usecols=['SignupDate', 'Gender', 'Age']
)
display(df_subset.head())

# 3. Parsing Dates on Import
# 'parse_dates' automatically converts standard string dates into Pandas datetime objects
df_dates = pd.read_csv(
    path + 'customers.csv', 
    parse_dates=['SignupDate']
)
display(df_dates.head())
print("Data type of 'date' column:", df_dates['SignupDate'].dtype)

# 4. Setting an Index Column
# 'index_col' assigns a specific column to act as the row labels immediately upon loading
df_indexed = pd.read_csv(
    path + 'customers.csv', 
    index_col='CustomerID'
)
display(df_indexed.head())

# 5. Handling Custom Missing Values
# 'na_values' tells pandas to treat specific strings or numbers (like '-999') as NaN
df_clean = pd.read_csv(
    path + 'customers.csv', 
    na_values=['Missing', 'Not Available', '-999', ' ']
)
display(df_clean.head())

,CustomerID,CustomerName,Gender,Age,Email,Phone,City,State,Country,Membership,SignupDate
0,107402,Priya Kulkarni,Male,32.0,priya.kulkarni77@gmail.com,9.709960e+09,Lucknow,Uttar Pradesh,India,Bronze,2021-05-05
1,105835,Ananya Banerjee,Male,47.0,ananya.banerjee593@yahoo.com,9.213418e+09,Chandigarh,Chandigarh,India,Bronze,2019-01-02
2,102123,Aarav Das,Male,48.0,aarav.das123@hotmail.com,9.310161e+09,Kochi,Kerala,India,Bronze,2020-08-03
3,108789,Diya Patel,Male,22.0,diya.patel68@hotmail.com,9.968083e+09,Lucknow,Uttar Pradesh,India,Platinum,2023-12-04
4,100305,Karan Yadav,Female,46.0,karan.yadav336@gmail.com,9.891291e+09,Jaipur,Rajasthan,India,Silver,2023-06-30

   Gender   Age  SignupDate
0    Male  32.0  2021-05-05
1    Male  47.0  2019-01-02
2    Male  48.0  2020-08-03
3    Male  22.0  2023-12-04
4  Female  46.0  2023-06-30

,CustomerID,CustomerName,Gender,Age,Email,Phone,City,State,Country,Membership,SignupDate
0,107402,Priya Kulkarni,Male,32.0,priya.kulkarni77@gmail.com,9.709960e+09,Lucknow,Uttar Pradesh,India,Bronze,2021-05-05
1,105835,Ananya Banerjee,Male,47.0,ananya.banerjee593@yahoo.com,9.213418e+09,Chandigarh,Chandigarh,India,Bronze,2019-01-02
2,102123,Aarav Das,Male,48.0,aarav.das123@hotmail.com,9.310161e+09,Kochi,Kerala,India,Bronze,2020-08-03
3,108789,Diya Patel,Male,22.0,diya.patel68@hotmail.com,9.968083e+09,Lucknow,Uttar Pradesh,India,Platinum,2023-12-04
4,100305,Karan Yadav,Female,46.0,karan.yadav336@gmail.com,9.891291e+09,Jaipur,Rajasthan,India,Silver,2023-06-30

Data type of 'date' column: datetime64[ns]

,CustomerName,Gender,Age,Email,Phone,City,State,Country,Membership,SignupDate
CustomerID,,,,,,,,,,
107402,Priya Kulkarni,Male,32.0,priya.kulkarni77@gmail.com,9.709960e+09,Lucknow,Uttar Pradesh,India,Bronze,2021-05-05
105835,Ananya Banerjee,Male,47.0,ananya.banerjee593@yahoo.com,9.213418e+09,Chandigarh,Chandigarh,India,Bronze,2019-01-02
102123,Aarav Das,Male,48.0,aarav.das123@hotmail.com,9.310161e+09,Kochi,Kerala,India,Bronze,2020-08-03
108789,Diya Patel,Male,22.0,diya.patel68@hotmail.com,9.968083e+09,Lucknow,Uttar Pradesh,India,Platinum,2023-12-04
100305,Karan Yadav,Female,46.0,karan.yadav336@gmail.com,9.891291e+09,Jaipur,Rajasthan,India,Silver,2023-06-30

,CustomerID,CustomerName,Gender,Age,Email,Phone,City,State,Country,Membership,SignupDate
0,107402,Priya Kulkarni,Male,32.0,priya.kulkarni77@gmail.com,9.709960e+09,Lucknow,Uttar Pradesh,India,Bronze,2021-05-05
1,105835,Ananya Banerjee,Male,47.0,ananya.banerjee593@yahoo.com,9.213418e+09,Chandigarh,Chandigarh,India,Bronze,2019-01-02
2,102123,Aarav Das,Male,48.0,aarav.das123@hotmail.com,9.310161e+09,Kochi,Kerala,India,Bronze,2020-08-03
3,108789,Diya Patel,Male,22.0,diya.patel68@hotmail.com,9.968083e+09,Lucknow,Uttar Pradesh,India,Platinum,2023-12-04
4,100305,Karan Yadav,Female,46.0,karan.yadav336@gmail.com,9.891291e+09,Jaipur,Rajasthan,India,Silver,2023-06-30

#### **10. How do you write a DataFrame to a CSV file?**
The `to_csv()` method exports your DataFrame back into a standard comma-separated text file. It gives you precise control over how row indices, column headers, and missing values are formatted on the disk.

In [10]:
import pandas as pd
import numpy as np

# Assume 'df' is the DataFrame you have been cleaning and processing
df = pd.DataFrame(
    {
        'City': ['Kolkata', 'Noida', 'Bengaluru', 'Hyderabad'],
        'AQI': ['100', '203', '147', '196'],
        'Status': ['Ok', 'Polluted', np.nan, 'Polluted'],
        'Population': [300000, 200000, np.nan, np.nan]
    }
)
# 1. Basic Export
# Writes the entire DataFrame to the current working directory.
# Note: By default, this saves the row index as the very first column in the CSV.
df.to_csv('processed_data.csv')

# 2. Export Without the Index (Most Common)
# Set index=False to prevent Pandas from writing the default numeric index (0, 1, 2...).
# This prevents an unnamed index column from appearing the next time you read the file.
df.to_csv('clean_data_no_index.csv', index=False)

# 3. Export Specific Columns
# Use the 'columns' parameter to save only a subset of your data.
df.to_csv(
    'subset_data.csv', 
    columns=['City', 'AQI', 'Status'], 
    index=False
)

# 4. Customizing Missing Data Representation
# 'na_rep' specifies how NaN values should appear in the text file. 
# By default, they are saved as empty strings. Here we replace them with 'NULL'.
df.to_csv(
    'data_with_nulls.csv', 
    index=False, 
    na_rep='NULL'
)

#### **11. How do you display the first few rows of a DataFrame?**
The `head()` method is used to quickly inspect the top rows of a DataFrame. This is an essential step immediately after loading data to verify the schema, column names, and data formats without printing thousands of rows to your screen.

In [11]:
import pandas as pd

# Creating a sample DataFrame with 6 rows
data = {
    'Station': ['Indiranagar', 'BTM Layout', 'HSR Layout', 'Koramangala', 'Whitefield', 'Jayanagar'],
    'AQI': [85, 112, 142, 110, 155, 92],
    'Status': ['Satisfactory', 'Poor', 'Very Poor', 'Poor', 'Very Poor', 'Satisfactory']
}
df = pd.DataFrame(data)

# 1. Default Usage
# By default, head() returns exactly the first 5 rows of the DataFrame
print("Default (First 5 rows):\n")
display(df.head())

# 2. Custom Row Count
# Pass an integer 'n' to view exactly that many rows from the top
print("\nFirst 3 rows:\n")
display(df.head(3))

# 3. Inspecting the Bottom Rows
# The tail() method works exactly like head(), but returns rows from the end of the dataset
# This is useful for checking if data appended correctly to the bottom of your file
print("\nLast 2 rows:\n")
display(df.tail(2))

Default (First 5 rows):

       Station  AQI        Status
0  Indiranagar   85  Satisfactory
1   BTM Layout  112          Poor
2   HSR Layout  142     Very Poor
3  Koramangala  110          Poor
4   Whitefield  155     Very Poor

First 3 rows:

       Station  AQI        Status
0  Indiranagar   85  Satisfactory
1   BTM Layout  112          Poor
2   HSR Layout  142     Very Poor

Last 2 rows:

      Station  AQI        Status
4  Whitefield  155     Very Poor
5   Jayanagar   92  Satisfactory

#### **12. How do you display the last few rows?**
The `tail()` method is the exact counterpart to `head()`, used to inspect the bottom rows of a DataFrame or Series. It is particularly useful for verifying the most recently appended data in chronological datasets or checking if summary/total rows were accidentally imported at the end of a CSV file.

In [12]:
import pandas as pd

# Creating a sample time-series DataFrame
data = {
    'Date': ['2026-09-07', '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11', '2026-09-12'],
    'Station': ['Kolkata Central'] * 6,
    'PM25_Level': [55.2, 58.1, 62.4, 70.1, 75.8, 80.2]
}
df = pd.DataFrame(data)

# 1. Default Usage
# By default, tail() returns exactly the last 5 rows of the DataFrame
print("Default (Last 5 rows):\n")
display(df.tail())

# 2. Custom Row Count
# Pass an integer 'n' to view exactly that many rows from the very bottom
print("\nLast 2 rows (Most recent data):\n")
display(df.tail(2))

# 3. Using tail() on a Single Column (Series)
# The method works identically on a 1D Series
print("\nLast 3 PM2.5 readings:\n")
print(df['PM25_Level'].tail(3))

Default (Last 5 rows):

         Date          Station  PM25_Level
1  2026-09-08  Kolkata Central        58.1
2  2026-09-09  Kolkata Central        62.4
3  2026-09-10  Kolkata Central        70.1
4  2026-09-11  Kolkata Central        75.8
5  2026-09-12  Kolkata Central        80.2

Last 2 rows (Most recent data):

         Date          Station  PM25_Level
4  2026-09-11  Kolkata Central        75.8
5  2026-09-12  Kolkata Central        80.2

Last 3 PM2.5 readings:

3    70.1
4    75.8
5    80.2
Name: PM25_Level, dtype: float64

#### **13. What does df.info() do?**
The `info()` method provides a concise structural summary of a DataFrame. It is the best diagnostic tool to run immediately after loading a dataset to check for missing values and ensure data types were parsed correctly.

**Key Diagnostic Information Provided**

* **Dimensions:** The total number of rows (index entries) and columns.
* **Data Types:** The `dtype` of each column (e.g., `int64`, `float64`, `object` for strings).
* **Non-Null Counts:** How many valid (non-missing) entries exist in each column, which instantly highlights where data is missing.
* **Memory Usage:** The RAM footprint of the DataFrame.

In [13]:
import pandas as pd
import numpy as np

# Creating a dataset with mixed types and missing values (NaN)
data = {
    'station_id': [101, 102, 103, 104],
    'city': ['Bengaluru', 'Kolkata', 'Chennai', 'Mumbai'],
    'pm25_level': [45.2, 55.1, np.nan, 80.2],  # Note the missing value here
    'is_active': [True, True, False, True]
}
df = pd.DataFrame(data)

# 1. Standard Info Summary
# Notice how 'pm25_level' will show 3 non-null out of 4 total rows
print("Standard df.info() Output:\n")
df.info()

# 2. Deep Memory Profiling
# By default, Pandas only estimates the memory of 'object' (string) columns. 
# Using memory_usage='deep' forces Pandas to inspect the exact memory footprint of all strings.
print("\nDeep Memory Profiling:\n")
df.info(memory_usage='deep')

Standard df.info() Output:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   station_id  4 non-null      int64
 1   city        4 non-null      object
 2   pm25_level  3 non-null      float64
 3   is_active   4 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 232.0+ bytes

Deep Memory Profiling:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   station_id  4 non-null      int64
 1   city        4 non-null      object
 2   pm25_level  3 non-null      float64
 3   is_active   4 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 425.0 bytes

#### **14. What does df.describe() return?**
The `describe()` method generates descriptive statistics that summarize the central tendency, dispersion, and shape of a dataset's distribution, automatically excluding `NaN` values. By default, it only profiles numeric columns (integers and floats), providing a rapid mathematical overview of your data.

**Numeric Output Metrics**
* **count:** Number of non-null observations.
* **mean:** The average value.
* **std:** Standard deviation (measure of data spread).
* **min / max:** The lowest and highest values.
* **25%, 50%, 75%:** The lower percentile, median (50%), and upper percentile.

In [14]:
import pandas as pd
import numpy as np

# Creating a dataset with both numeric and categorical data
data = {
    'station': ['Indiranagar', 'BTM Layout', 'HSR Layout', 'Koramangala', 'Whitefield'],
    'aqi': [85, 112, 142, 110, 155],
    'pm25_level': [45.2, 55.1, 70.4, np.nan, 82.5],
    'status': ['Satisfactory', 'Poor', 'Very Poor', 'Poor', 'Very Poor']
}
df = pd.DataFrame(data)

# 1. Default Behavior (Numeric Columns Only)
print("Numeric Statistics:\n")
display(df.describe())

# 2. Profiling Categorical/String Data
# Passing include='object' forces describe() to analyze string columns.
# It returns count, number of unique values, the most frequent value (top), 
# and its frequency (freq).
print("\nCategorical Statistics:\n")
display(df.describe(include=['object']))

# 3. Profiling All Columns
# Passing include='all' analyzes every column, filling cells with NaN 
# where a metric doesn't apply (e.g., 'mean' for a string column).
print("\nAll Columns Summary:\n")
display(df.describe(include='all'))

Numeric Statistics:

              aqi  pm25_level
count    5.000000    4.000000
mean   120.800000   63.300000
std     27.815463   16.471187
min     85.000000   45.200000
25%    110.000000   52.625000
50%    112.000000   62.750000
75%    142.000000   73.425000
max    155.000000   82.500000

Categorical Statistics:

            station status
count             5      5
unique            5      3
top     Indiranagar   Poor
freq              1      2

All Columns Summary:

            station         aqi  pm25_level status
count             5    5.000000    4.000000      5
unique            5         NaN         NaN      3
top     Indiranagar         NaN         NaN   Poor
freq              1         NaN         NaN      2
mean            NaN  120.800000   63.300000    NaN
std             NaN   27.815463   16.471187    NaN
min             NaN   85.000000   45.200000    NaN
25%             NaN  110.000000   52.625000    NaN
50%             NaN  112.000000   62.750000    NaN
75%             NaN  142.000000   73.425000    NaN
max             NaN  155.000000   82.500000    NaN

#### **15. How do you check the shape of a DataFrame?**
The `shape` attribute returns a tuple representing the dimensionality of the DataFrame in the format `(rows, columns)`. Because it is an underlying property of the DataFrame rather than a functional method, you do not use parentheses when calling it.

**Key Characteristics**
* **Zero-Indexed Tuple:** The first element `[0]` represents the total number of rows (index length), and the second element `[1]` represents the total number of columns.
* **Series Shape:** If called on a 1D Series, it returns a tuple with a single element: `(rows,)`.

In [15]:
import pandas as pd

# Creating a dataset with 4 rows and 3 columns
data = {
    'Station': ['BTM Layout', 'HSR Layout', 'Koramangala', 'Indiranagar'],
    'PM10_Level': [102.4, 89.1, 76.5, 95.0],
    'Status': ['Moderate', 'Satisfactory', 'Satisfactory', 'Moderate']
}
df = pd.DataFrame(data)

# 1. Getting the full shape tuple
dimensions = df.shape
print(f"Full Shape Tuple: {dimensions}")

# 2. Extracting rows and columns programmatically
# Useful when setting up loops or validating data sizes before machine learning pipelines
num_rows = df.shape[0]
num_cols = df.shape[1]

print(f"Total Rows: {num_rows}")
print(f"Total Columns: {num_cols}")

# 3. Checking the shape of a single column (Series)
series_shape = df['PM10_Level'].shape
print(f"Series Shape: {series_shape}")

Full Shape Tuple: (4, 3)
Total Rows: 4
Total Columns: 3
Series Shape: (4,)

#### **16. How do you list column names?**
The `columns` attribute returns the column labels of a DataFrame. Like `shape`, it is an attribute rather than a method, so you do not use parentheses. By default, it returns a pandas `Index` object, but it can easily be converted into a standard Python list.

**Key Characteristics**
* **Index Object:** The returned object is optimized for pandas operations but behaves similarly to a list.
* **Iterable:** You can easily loop through the `columns` attribute to apply bulk text formatting (like converting all names to lowercase).

In [16]:
import pandas as pd

# Creating a sample dataset
data = {
    'Station_ID': ['BTM', 'HSR', 'KOR'],
    'PM25_Level': [45.2, 55.1, 70.4],
    'Air_Quality_Index': [85, 112, 142]
}
df = pd.DataFrame(data)

# 1. Accessing the columns attribute directly
print("Raw Columns Index Object:")
print(df.columns)

# 2. Converting to a standard Python list (Most Common)
# Using .tolist() is the preferred way to extract headers for iteration or manipulation
col_list = df.columns.tolist()
print("\nAs a Python List:")
print(col_list)

# 3. Iterating through column names
# Useful for bulk renaming, such as converting all headers to lowercase
print("\nIterating through columns:")
for col in df.columns:
    print(f" - {col.lower()}")

# 4. Modifying column names directly
# You can overwrite the entire columns attribute by assigning a list of the exact same length
df.columns = ['station', 'pm25', 'aqi']
print("\nRenamed Columns:")
print(df.columns.tolist())

Raw Columns Index Object:
Index(['Station_ID', 'PM25_Level', 'Air_Quality_Index'], dtype='object')

As a Python List:
['Station_ID', 'PM25_Level', 'Air_Quality_Index']

Iterating through columns:
 - station_id
 - pm25_level
 - air_quality_index

Renamed Columns:
['station', 'pm25', 'aqi']

#### **17. How do you check data types of columns?**
The `dtypes` attribute returns a Series displaying the specific data type of each column in your DataFrame. Understanding these types is critical, as mathematical functions will fail on string columns, and date functions will fail if a date is stored as an `object` (string) instead of a `datetime` object.

**Common Pandas Data Types**
* **`int64` / `float64`:** Integer and floating-point numbers.
* **`object`:** Typically represents strings, but can also indicate a column containing mixed data types.
* **`bool`:** True/False boolean values.
* **`datetime64`:** Date and time values, which unlock time-series methods.

In [17]:
import pandas as pd

# Creating a dataset with a variety of data types
data = {
    'station_name': ['Bally', 'New Town', 'Salt Lake'], # object (string)
    'aqi': [110, 85, 92],                               # int64
    'pm25_level': [45.2, 38.1, 40.5],                   # float64
    'is_active': [True, True, False],                   # bool
    'last_calibrated': ['2026-08-01', '2026-08-15', '2026-09-01'] # object (currently a string)
}
df = pd.DataFrame(data)

# Convert the string column to actual datetime objects
df['last_calibrated'] = pd.to_datetime(df['last_calibrated'])

# 1. Checking all data types
# Returns a Pandas Series where the index is column names and values are the data types
print("Data types for all columns:\n")
print(df.dtypes)

# 2. Checking a single column's data type
print(f"\nData type of 'pm25_level': {df['pm25_level'].dtype}")

# 3. Filtering columns by data type
# select_dtypes() allows you to isolate columns for specific operations 
# (e.g., extracting only numeric columns before applying a scaling algorithm)
numeric_df = df.select_dtypes(include=['int64', 'float64'])
print("\nNumeric columns only:\n")
display(numeric_df)

# You can also use 'number' as a shortcut for all int/float types, 
# or use 'exclude' to drop certain types
text_only = df.select_dtypes(exclude=['number', 'bool', 'datetime64'])
print("\nText (object) columns only:\n")
display(text_only)

Data types for all columns:

station_name               object
aqi                         int64
pm25_level                float64
is_active                    bool
last_calibrated    datetime64[ns]
dtype: object

Data type of 'pm25_level': float64

Numeric columns only:

   aqi  pm25_level
0  110        45.2
1   85        38.1
2   92        40.5

Text (object) columns only:

  station_name
0        Bally
1     New Town
2    Salt Lake

#### **18. How do you rename columns?**
You can rename columns in Pandas by either mapping specific column names using a dictionary or by completely overwriting the column index array.

**Common Renaming Methods**
* **The `rename()` Method:** The safest approach. It uses a dictionary to target specific columns, leaving unspecified columns untouched regardless of their order.
* **Index Assignment:** Overwrites the entire `df.columns` attribute at once. It is fast but requires providing a list that exactly matches the total number of columns.
* **Vectorized String Operations:** Applies string methods (like lowercase or replace) across the entire column index simultaneously, which is ideal for cleaning messy, inconsistent headers.

In [18]:
import pandas as pd

# Creating a sample dataset with messy, capitalized column names containing spaces
data = {
    'Station Name': ['Salt Lake', 'New Town'],
    'PM2.5': [45.2, 38.1],
    'AQI Level': [92, 85]
}
df = pd.DataFrame(data)
print("Original Columns:", df.columns.tolist())

# 1. Using rename() with a Dictionary (Targeted approach)
# Keys are the old names, values are the new names.
# This returns a new DataFrame unless you pass inplace=True.
df_renamed = df.rename(columns={
    'Station Name': 'station', 
    'PM2.5': 'pm25'
})
print("\nTargeted Rename:")
display(df_renamed)

# 2. Overwriting the columns attribute (Complete replacement)
# The provided list must match the exact number of columns in the DataFrame.
df.columns = ['station_id', 'pm25_reading', 'aqi_score']
print("\nFull Overwrite:")
display(df)

# 3. Bulk Vectorized String Operations (Automated cleanup)
# Ideal for standardizing hundreds of columns without typing them out manually.
df_raw = pd.DataFrame(data)

# Convert all headers to lowercase, replace spaces with underscores, and remove periods
df_raw.columns = (
    df_raw.columns
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('.', '')
)

print("\nAutomated String Cleanup:")
display(df_raw)

Original Columns: ['Station Name', 'PM2.5', 'AQI Level']

Targeted Rename:

     station  pm25  AQI Level
0  Salt Lake  45.2         92
1   New Town  38.1         85

Full Overwrite:

  station_id  pm25_reading  aqi_score
0  Salt Lake          45.2         92
1   New Town          38.1         85

Automated String Cleanup:

  station_name  pm25  aqi_level
0    Salt Lake  45.2         92
1     New Town  38.1         85

#### **19. How do you select a single column?**
You can select a single column from a DataFrame using either bracket notation or dot notation. Both methods extract the column and return it as a 1-Dimensional Pandas Series.

**Selection Methods**
* **Bracket Notation (`df['Column Name']`):** The safest and most universally recommended method. It successfully handles column names that contain spaces, special characters, or names that conflict with built-in Pandas methods.
* **Dot Notation (`df.Column_Name`):** A faster shorthand commonly used in exploratory analysis. However, it *only* works if the column name is a valid Python variable (no spaces) and does not conflict with existing Pandas methods (like `min`, `shape`, or `count`).

In [19]:
import pandas as pd

# Creating a dataset with a mix of safe and complex column names
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake'],
    'aqi': [115, 85, 92],
    'PM 2.5 Level': [48.2, 38.1, 40.5], # Contains spaces and special characters
    'count': [1, 2, 3]                  # Conflicts with the DataFrame.count() method
}
df = pd.DataFrame(data)

# 1. Bracket Notation (Recommended)
# Works perfectly for any string
aqi_series = df['aqi']
print("Bracket Notation Output:\n", aqi_series)

# 2. Dot Notation (Convenience)
# Works only for valid variable names without spaces
station_series = df.station
print("\nDot Notation Output:\n", station_series)

# 3. Handling Complex Names
# df.PM 2.5 Level would throw a SyntaxError. You MUST use brackets here.
pm_series = df['PM 2.5 Level']

# 4. Method Conflicts
# df.count returns the built-in counting method, NOT your data column.
# To get your actual data column named 'count', you must use brackets.
actual_count_data = df['count']

# 5. Verifying the Object Type
# Extracting a single column always returns a Series
print(f"\nType of extracted column: {type(aqi_series)}")

Bracket Notation Output:
 0    115
1     85
2     92
Name: aqi, dtype: int64

Dot Notation Output:
 0       Howrah
1     New Town
2    Salt Lake
Name: station, dtype: object

Type of extracted column: <class 'pandas.core.series.Series'>

#### **20. How do you select multiple columns?**
You can select multiple columns by passing a Python list of column names inside the standard DataFrame indexing brackets. This creates a "double bracket" syntax `df[['col1', 'col2']]` and always returns a new DataFrame rather than a Series.

**Key Characteristics**
* **Double Brackets:** The outer brackets represent the indexing operation, while the inner brackets contain the Python list of column strings.
* **Output Type:** Because you are extracting multiple dimensions, the result is always a 2-Dimensional DataFrame.
* **Column Reordering:** The columns in the new DataFrame will appear in the exact order you specify in your list, which provides a fast way to reorder your dataset on the fly.

In [20]:
import pandas as pd

# Creating a sample dataset
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake'],
    'aqi': [115, 85, 92],
    'pm25_level': [48.2, 38.1, 40.5],
    'temperature_c': [31, 32, 30]
}
df = pd.DataFrame(data)

# 1. Standard Multiple Selection (Double Brackets)
# Pass a list of column names directly into the indexing brackets
subset_df = df[['station', 'aqi']]
print("Multiple Column Extraction:\n")
display(subset_df)

# 2. Using a Variable List
# This approach is much cleaner when extracting many columns or dynamically generating the list
target_columns = ['station', 'temperature_c', 'pm25_level']
reordered_df = df[target_columns]

print("\nExtraction Using a List Variable (Note the new column order):\n")
display(reordered_df)

# 3. Verifying the Object Type
print(f"\nType of multiple extracted columns: {type(subset_df)}")

# 4. Forcing a Single Column into a DataFrame
# If you use double brackets on a single column name, Pandas returns a 2D DataFrame 
# instead of a 1D Series. This is often required when feeding single features into Scikit-Learn.
single_col_df = df[['aqi']]
print(f"Type of single column with double brackets: {type(single_col_df)}")

Multiple Column Extraction:

     station  aqi
0     Howrah  115
1   New Town   85
2  Salt Lake   92

Extraction Using a List Variable (Note the new column order):

     station  temperature_c  pm25_level
0     Howrah             31        48.2
1   New Town             32        38.1
2  Salt Lake             30        40.5

Type of multiple extracted columns: <class 'pandas.core.frame.DataFrame'>
Type of single column with double brackets: <class 'pandas.core.frame.DataFrame'>

## Intermediate Level (21–50)

#### **21. What is the difference between loc[] and iloc[]?**

#### **22. What is label-based indexing?**

#### **23. What is integer-based indexing?**

#### **24. How do you filter rows based on conditions?**

#### **25. How do you select rows with multiple conditions?**

#### **26. What is boolean indexing?**

#### **27. How do you sort a DataFrame?**

#### **28. What is the difference between sort_values() and sort_index()?**

#### **29. How do you remove duplicate rows?**

#### **30. How do you count duplicates?**

#### **31. How do you handle missing values?**

#### **32. Difference between dropna() and fillna()?**

#### **33. How do you replace missing values with the mean?**

#### **34. How do you detect missing values?**

#### **35. Difference between isna() and notna()?**

#### **36. How do you add a new column?**

#### **37. How do you delete a column?**

#### **38. Difference between drop() and del?**

#### **39. How do you change data types?**

#### **40. What is astype()?**

#### **41. How do you apply a function to a column?**

#### **42. What is apply()?**

#### **43. Difference between apply(), map(), and applymap()?**

#### **44. What is value_counts()?**

#### **45. What is unique()?**

#### **46. What is nunique()?**

#### **47. How do you rename index values?**

#### **48. How do you reset the index?**

#### **49. What is set_index()?**

#### **50. Why are indexes important?**

## Data Manipulation (51–70)

#### **51. What is groupby()?**

#### **52. How does groupby() work internally?**

#### **53. Difference between aggregation and transformation?**

#### **54. What are aggregation functions?**

#### **55. How do you calculate multiple aggregations?**

#### **56. What is pivot_table()?**

#### **57. Difference between pivot() and pivot_table()?**

#### **58. What is melting?**

#### **59. What is melt()?**

#### **60. What is stack()?**

#### **61. What is unstack()?**

#### **62. Difference between long and wide data?**

#### **63. What is explode()?**

#### **64. What is crosstab()?**

#### **65. What is cut()?**

#### **66. What is qcut()?**

#### **67. How do you bin continuous data?**

#### **68. What is transform()?**

#### **69. Difference between transform() and aggregate()?**

#### **70. What is pipe()?**

## Merge, Join & Combine (71–85)

#### **71. Difference between merge(), join(), and concat()?**

#### **72. Explain different types of joins.**

#### **73. What is an inner join?**

#### **74. What is a left join?**

#### **75. What is a right join?**

#### **76. What is a full outer join?**

#### **77. What happens when merge keys have duplicates?**

#### **78. How do you merge on multiple columns?**

#### **79. How do you concatenate DataFrames vertically?**

#### **80. How do you concatenate horizontally?**

#### **81. What is hierarchical indexing?**

#### **82. What is a MultiIndex?**

#### **83. How do you flatten a MultiIndex?**

#### **84. What is combine_first()?**

#### **85. How do you compare two DataFrames?**

## Advanced Level (86–100)

#### **86. How is a DataFrame stored in memory?**

#### **87. Why is Pandas slower than NumPy for numerical operations?**

#### **88. What is vectorization in Pandas?**

#### **89. When should you avoid using apply()?**

#### **90. How can you optimize large DataFrames?**

#### **91. What are categorical data types, and when should you use them?**

#### **92. How do you reduce memory usage in a DataFrame?**

#### **93. What are time series in Pandas?**

#### **94. How do you work with datetime columns?**

#### **95. What is resampling?**

#### **96. What is rolling window analysis?**

#### **97. How do you handle time zones in Pandas?**

#### **98. How would you process a 10 GB CSV that doesn't fit into memory?**

#### **99. What are common performance bottlenecks in Pandas, and how can you address them?**

#### **100. In what situations would you choose Pandas over NumPy, and when would you choose NumPy instead?**

## Frequently Asked Scenario-Based Questions

#### **101. How would you clean a messy dataset before analysis?**

#### **102. How do you identify and remove duplicate records?**

#### **103. How would you fill missing values differently for numerical and categorical columns?**

#### **104. How do you detect and handle outliers using Pandas?**

#### **105. How would you find the top 5 customers by total sales?**

#### **106. How would you calculate month-over-month growth from a sales dataset?**

#### **107. How do you combine data from multiple CSV files into one DataFrame?**

#### **108. How would you reshape a dataset from wide format to long format?**

#### **109. How do you optimize a slow Pandas script processing millions of rows?**

#### **110. What are the most common mistakes developers make when working with Pandas?**