## Basic Level (1–20)

#### **1. What is pandas?**
Pandas is an open-source Python library designed for high-performance data manipulation, analysis, and cleaning. Built on top of the NumPy library, it acts as the backbone for most data science and machine learning workflows in Python.

**Core Data Structures**

* **Series:** A one-dimensional labeled array capable of holding any data type (integer, string, float, python objects, etc.). Think of it as a single column in a table.
* **DataFrame:** A two-dimensional, size-mutable, tabular data structure with labeled axes (rows and columns). It is the primary pandas object and functions like a highly powered Excel spreadsheet or SQL table.

**Why It Is Essential**

* **I/O Operations:** It seamlessly reads and writes data from multiple formats, including CSV, Excel, SQL databases, Parquet, and JSON.
* **Data Cleaning:** It provides built-in methods for handling missing data (`NaN`), dropping duplicates, and standardizing data types.
* **Data Transformation:** It allows for effortless slicing, filtering, reshaping, aggregating (groupby), and merging of disparate datasets.
* **Time Series Analysis:** It includes native tools for date range generation, frequency conversion, and moving window statistics.

In [1]:
# Importing Pandas in Python
import pandas as pd

#### **2. Why is Pandas used in Data Science?**
Pandas bridges the gap between raw, unstructured data and the clean datasets required for training machine learning models. It streamlines the exploratory data analysis and feature engineering steps that typically consume the majority of a data science workflow.

* **Ecosystem Integration:** Acts as the central data hub, seamlessly passing structured matrices to Scikit-learn, TensorFlow, or PyTorch, and feeding visual libraries like Matplotlib and Seaborn.
* **Vectorized Performance:** Built on a C backend, it replaces slow Python `for` loops with optimized, vectorized operations for rapid data transformations and mathematical calculations.
* **Heterogeneous Data:** Unlike strict numerical arrays, DataFrames effortlessly manage combinations of integers, floats, categorical strings, and time-series data in a single table.
* **Complex Aggregations:** Simplifies SQL-like operations—such as multi-level `groupby` aggregations, joins, and pivot tables—allowing you to extract analytical insights with minimal code.
* **Automated Alignment:** Automatically aligns data by label during arithmetic operations and merges, preventing critical index-mismatch errors when combining different datasets.
* **Handling Incompleteness:** Provides native, highly flexible methods to detect, drop, or impute missing values (`NaN`), which is crucial for real-world datasets before they reach an algorithm.

#### **3. What are the main data structures in Pandas?**
Pandas relies on two foundational data structures: the **Series** (1-dimensional) and the **DataFrame** (2-dimensional). Every operation in Pandas is essentially manipulating one or both of these structures.

**1. Series (1-Dimensional)**
A Series is a one-dimensional array-like object capable of holding any single data type (integers, strings, floats, objects). It consists of two main components: the actual data array and an associated array of data labels, called its *index*.

**2. DataFrame (2-Dimensional)**
A DataFrame is a two-dimensional, size-mutable tabular structure with rows and columns. You can think of it as a dictionary of aligned Series objects that all share the same index. This is the most commonly used pandas object.

**Core Differences**  
| Feature | Series | DataFrame |
| --- | --- | --- |
| **Dimensions** | 1D (Array/List-like) | 2D (Table/Grid-like) |
| **Data Types** | Homogeneous (single data type per Series) | Heterogeneous (each column can be a different data type) |
| **Structure** | Single column of data with an Index | Multiple columns of data, sharing a single Index |
| **Size Mutability** | Fixed size (adding elements requires recreating) | Mutable (easily add or drop rows/columns) |

In [2]:
import pandas as pd

# Creating a Series from a list with a custom string index
pm25_values = pd.Series(
    [45.2, 112.5, 89.0], 
    index=['Morning', 'Afternoon', 'Evening'], 
    name='PM2.5_Levels'
)

print(pm25_values)
print("\nAccessing by index label:", pm25_values['Afternoon'])

Morning       45.2
Afternoon    112.5
Evening       89.0
Name: PM2.5_Levels, dtype: float64

Accessing by index label: 112.5

In [3]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Date': ['2026-09-10', '2026-09-11', '2026-09-12'],
    'Station': ['Zone A', 'Zone B', 'Zone A'],
    'AQI': [85, 142, 90],
    'Status': ['Good', 'Poor', 'Satisfactory']
}

df = pd.DataFrame(data)

# Setting a specific column as the row index
df.set_index('Date', inplace=True)

display(df)

# Extracting a single column returns a Series
print("\nType of a single column:", type(df['AQI']))

           Station  AQI        Status
Date
2026-09-10  Zone A   85          Good
2026-09-11  Zone B  142          Poor
2026-09-12  Zone A   90  Satisfactory

Type of a single column: <class 'pandas.core.series.Series'>

#### **4. What is a Series?**
A **Series** is a one-dimensional, labeled array capable of holding any data type (integers, strings, floating-point numbers, Python objects). Think of it as a single column in a spreadsheet, where every row has a specific, immutable label.

**Key Characteristics**
* **The Index:** Unlike a standard Python list, every element in a Series has an explicit, customizable label (the index). If you don't provide one, Pandas assigns a default sequence (`0, 1, 2...`).
* **Data Homogeneity:** While it *can* hold mixed types (which forces the overall type to `object`), a Series is highly optimized when holding a single data type, allowing for memory efficiency and high-speed calculations.
* **Dual Behavior:** A Series acts like a hybrid between a Python dictionary (key-value pairs via the index) and a NumPy array (vectorized math operations).

In [4]:
import pandas as pd

# 1. Creating a Series from a standard list (receives a default integer index)
cities = pd.Series(['Bengaluru', 'Kolkata', 'Chennai', 'Mumbai'])
print("Default Index Series:\n", cities)

# 2. Creating a Series from a dictionary (dictionary keys automatically become the index)
air_quality_dict = {'Indiranagar': 85, 'HSR Layout': 142, 'Koramangala': 110}
aqi_series = pd.Series(air_quality_dict, name='AQI_Readings')
print("\nDictionary to Series:\n", aqi_series)

# 3. Accessing elements (Dictionary-like behavior)
print("\nAQI in HSR Layout:", aqi_series['HSR Layout'])

# 4. Vectorized Math (NumPy-like behavior)
# Adjusting every value simultaneously without writing a 'for' loop
adjusted_aqi = aqi_series + 10
print("\nAdjusted AQI (+10):\n", adjusted_aqi)

# 5. Boolean Filtering
# Selecting only the items that meet a specific condition
high_pollution = aqi_series[aqi_series > 100]
print("\nLocations with AQI > 100:\n", high_pollution)

Default Index Series:
 0    Bengaluru
1      Kolkata
2      Chennai
3       Mumbai
dtype: object

Dictionary to Series:
 Indiranagar     85
HSR Layout     142
Koramangala    110
Name: AQI_Readings, dtype: int64

AQI in HSR Layout: 142

Adjusted AQI (+10):
 Indiranagar     95
HSR Layout     152
Koramangala    120
Name: AQI_Readings, dtype: int64

Locations with AQI > 100:
 HSR Layout     142
Koramangala    110
Name: AQI_Readings, dtype: int64

#### **5. What is a DataFrame?**
A **DataFrame** is a two-dimensional, tabular data structure composed of rows and columns, functioning much like a SQL table or an Excel spreadsheet. Under the hood, it is essentially a dictionary of Pandas Series objects that all share the exact same row index.

**Key Characteristics**
* **Heterogeneous Types:** Unlike standard NumPy matrices, each column in a DataFrame can hold a entirely different data type (e.g., a string column next to a float column).
* **Labeled Axes:** Both rows (the index) and columns have explicit labels, allowing for intuitive data alignment, merging, and retrieval.
* **Size-Mutable:** You can dynamically append rows or insert/delete columns without needing to recreate the entire object.

In [5]:
import pandas as pd

# 1. Creating a DataFrame from a dictionary of lists (most common method)
# Each key becomes a column name, and each list becomes the column's data
data = {
    'City': ['Kolkata', 'Bengaluru', 'Chennai'],
    'PM10_Level': [102.4, 89.1, 76.5],
    'Status': ['Moderate', 'Satisfactory', 'Satisfactory']
}
df = pd.DataFrame(data)

print("Standard DataFrame:\n")
display(df)

# 2. Accessing components
# Extracting a single column returns a Series
pm10_series = df['PM10_Level']

# Extracting multiple columns returns a smaller DataFrame
subset_df = df[['City', 'Status']]

# 3. Adding a new column
# You can broadcast a single value or assign a calculated array/list
df['Country'] = 'India'
df['Requires_Action'] = df['PM10_Level'] > 100

print("\nDataFrame after adding columns:\n")
display(df)

# 4. Exploring the underlying structure
print("\nDataFrame Index:", df.index)
print("DataFrame Columns:", df.columns)
print("DataFrame Shape (Rows, Columns):", df.shape)

Standard DataFrame:

        City  PM10_Level        Status
0    Kolkata       102.4      Moderate
1  Bengaluru        89.1  Satisfactory
2    Chennai        76.5  Satisfactory

DataFrame after adding columns:

        City  PM10_Level        Status Country  Requires_Action
0    Kolkata       102.4      Moderate   India             True
1  Bengaluru        89.1  Satisfactory   India            False
2    Chennai        76.5  Satisfactory   India            False

DataFrame Index: RangeIndex(start=0, stop=3, step=1)
DataFrame Columns: Index(['City', 'PM10_Level', 'Status', 'Country', 'Requires_Action'], dtype='object')
DataFrame Shape (Rows, Columns): (3, 5)

#### **6. What is the difference between a Series and a DataFrame?**
The fundamental difference lies in dimensionality: a Series represents a single column of data (1D), whereas a DataFrame is a multi-column table (2D) composed of multiple aligned Series. Every column you extract from a DataFrame is returned as a Series.

**Key Structural Differences**

| Feature | `pd.Series` | `pd.DataFrame` |
| --- | --- | --- |
| **Dimensions** | 1-Dimensional (Array/List-like) | 2-Dimensional (Table/Grid-like) |
| **Data Types** | Homogeneous (typically a single data type) | Heterogeneous (each column can be a different type) |
| **Conceptual Model** | A single column of data with row labels (index) | A dictionary of Series objects sharing the exact same index |
| **Size Mutability** | Fixed size (adding elements usually requires recreating the object) | Mutable (add or drop columns and rows dynamically) |

In [6]:
import pandas as pd

# 1. Start with a DataFrame (2D)
data = {
    'Station': ['Indiranagar', 'BTM Layout', 'HSR Layout'],
    'PM25_Level': [45.2, 112.5, 89.0]
}
df = pd.DataFrame(data)
print("Original Object Type:", type(df))

# 2. Extracting a single column returns a Series (1D)
pm25_series = df['PM25_Level']
print("\nExtracted Column Type:", type(pm25_series))

# 3. Creating an independent Series
# If you don't specify an index, it defaults to 0, 1, 2... matching the DataFrame
aqi_status = pd.Series(['Good', 'Poor', 'Moderate'], name='Status')
print("\nIndependent Series:\n", aqi_status)

# 4. Combining them: Adding the Series as a new column in the DataFrame
df['AQI_Status'] = aqi_status
print("\nCombined DataFrame:\n")
display(df)

Original Object Type: <class 'pandas.core.frame.DataFrame'>

Extracted Column Type: <class 'pandas.core.series.Series'>

Independent Series:
 0        Good
1        Poor
2    Moderate
Name: Status, dtype: object

Combined DataFrame:

       Station  PM25_Level AQI_Status
0  Indiranagar        45.2       Good
1   BTM Layout       112.5       Poor
2   HSR Layout        89.0   Moderate

#### **7. How do you create a Series?**
You can create a Pandas Series by passing various Python or NumPy data structures into the `pd.Series()` constructor. The constructor accepts the data itself, an optional custom index, and an optional name for the Series.

**Common Data Sources for a Series**
* **Python Lists:** Automatically assigned a numeric index (0, 1, 2...) unless a custom index is provided.
* **Python Dictionaries:** The dictionary keys automatically become the Series index, and the values become the data.
* **NumPy Arrays:** Functions exactly like a list, leveraging NumPy's memory efficiency.
* **Scalar Values:** A single value (like an integer or string) that gets repeated across a provided index.

In [7]:
import pandas as pd
import numpy as np

# 1. Creating from a standard list (default integer index)
kit_sizes = pd.Series(['S', 'S', 'S', 'S'], name='Kit_Size')
print("From List (Default Index):\n", kit_sizes)

# 2. Creating from a list with a custom index
# The length of the index list must exactly match the length of the data list
squad_numbers = pd.Series(
    [10, 11, 10, 11], 
    index=['Messi', 'Raphinha', 'Mac Allister', 'Di Maria'],
    name='Squad_Number'
)
print("\nFrom List (Custom Index):\n", squad_numbers)

# 3. Creating from a Dictionary
# Pandas automatically uses the dictionary keys as the index labels
player_teams = {
    'Messi': 'Argentina',
    'Raphinha': 'FC Barcelona',
    'Mac Allister': 'Liverpool',
    'Di Maria': 'Argentina'
}
team_series = pd.Series(player_teams, name='Team')
print("\nFrom Dictionary:\n", team_series)

# 4. Creating from a NumPy array
# Useful when pulling data generated by mathematical functions
random_data = np.array([4.5, 8.2, 9.1])
np_series = pd.Series(random_data, index=['x', 'y', 'z'])
print("\nFrom NumPy Array:\n", np_series)

# 5. Creating from a Scalar value
# The single value 'Economy' is broadcasted across all provided index labels
flight_class = pd.Series('Economy', index=['Flight_1', 'Flight_2', 'Flight_3'])
print("\nFrom Scalar Value:\n", flight_class)

From List (Default Index):
 0    S
1    S
2    S
3    S
Name: Kit_Size, dtype: object

From List (Custom Index):
 Messi           10
Raphinha        11
Mac Allister    10
Di Maria        11
Name: Squad_Number, dtype: int64

From Dictionary:
 Messi              Argentina
Raphinha        FC Barcelona
Mac Allister       Liverpool
Di Maria           Argentina
Name: Team, dtype: object

From NumPy Array:
 x    4.5
y    8.2
z    9.1
dtype: float64

From Scalar Value:
 Flight_1    Economy
Flight_2    Economy
Flight_3    Economy
dtype: object

#### **8. How do you create a DataFrame?**
You can construct a DataFrame from scratch using several native Python data structures, though the most common approach is using a dictionary of lists. The `pd.DataFrame()` constructor automatically aligns the provided data into rows and columns.

**Common Data Sources for a DataFrame**
* **Dictionary of Lists:** Column-oriented creation where keys become column headers and lists become the column data.
* **List of Dictionaries:** Row-oriented creation where each dictionary represents a single row (useful when parsing JSON data).
* **2D NumPy Arrays:** Converts mathematical matrices into labeled tables by explicitly providing column and index names.
* **External Files:** In practice, you will most often create DataFrames by reading files using functions like `pd.read_csv()` or `pd.read_excel()`.

In [8]:
import pandas as pd
import numpy as np

# 1. From a Dictionary of Lists (Column-oriented)
# All lists must be the exact same length.
dict_data = {
    'City': ['Bengaluru', 'Kolkata', 'Chennai'],
    'AQI': [85, 102, 76],
    'Status': ['Satisfactory', 'Moderate', 'Satisfactory']
}
df_from_dict = pd.DataFrame(dict_data)
print("From Dictionary of Lists:\n")
display(df_from_dict)

# 2. From a List of Dictionaries (Row-oriented)
# Missing keys in specific dictionaries will automatically become NaN values.
list_data = [
    {'City': 'Bengaluru', 'AQI': 85},
    {'City': 'Kolkata', 'AQI': 102, 'Status': 'Moderate'},
    {'City': 'Chennai', 'AQI': 76, 'Status': 'Satisfactory'}
]
df_from_list = pd.DataFrame(list_data)
print("\nFrom List of Dictionaries:\n")
display(df_from_list)

# 3. From a 2D NumPy Array
# You must explicitly define the column names and index labels, otherwise they default to 0, 1, 2...
numpy_matrix = np.array([
    [85, 45.2], 
    [102, 55.1], 
    [76, 30.5]
])
df_from_numpy = pd.DataFrame(
    numpy_matrix, 
    columns=['AQI', 'PM2.5'], 
    index=['Bengaluru', 'Kolkata', 'Chennai']
)
print("\nFrom 2D NumPy Array:\n")
display(df_from_numpy)

From Dictionary of Lists:

        City  AQI        Status
0  Bengaluru   85  Satisfactory
1    Kolkata  102      Moderate
2    Chennai   76  Satisfactory

From List of Dictionaries:

        City  AQI        Status
0  Bengaluru   85           NaN
1    Kolkata  102      Moderate
2    Chennai   76  Satisfactory

From 2D NumPy Array:

             AQI  PM2.5
Bengaluru   85.0   45.2
Kolkata    102.0   55.1
Chennai     76.0   30.5

#### **9. How do you read data from a CSV file?**
The `pd.read_csv()` function is the workhorse for data ingestion in Pandas. It reads comma-separated values and converts them directly into a DataFrame, offering dozens of parameters to handle dates, specific columns, and missing values on the fly.

*(Note: You would need a local file named `customers.csv` to execute these exact commands).*

In [9]:
import pandas as pd

path = "./../Datasets/"
# 1. Basic Import
# Reads the entire file, assuming the first row contains column headers
df = pd.read_csv(path + 'customers.csv')
display(df.head())

# 2. Reading Specific Columns
# 'usecols' saves memory by only loading the columns you actually need for your analysis
df_subset = pd.read_csv(
    path + 'customers.csv', 
    usecols=['SignupDate', 'Gender', 'Age']
)
display(df_subset.head())

# 3. Parsing Dates on Import
# 'parse_dates' automatically converts standard string dates into Pandas datetime objects
df_dates = pd.read_csv(
    path + 'customers.csv', 
    parse_dates=['SignupDate']
)
display(df_dates.head())
print("Data type of 'date' column:", df_dates['SignupDate'].dtype)

# 4. Setting an Index Column
# 'index_col' assigns a specific column to act as the row labels immediately upon loading
df_indexed = pd.read_csv(
    path + 'customers.csv', 
    index_col='CustomerID'
)
display(df_indexed.head())

# 5. Handling Custom Missing Values
# 'na_values' tells pandas to treat specific strings or numbers (like '-999') as NaN
df_clean = pd.read_csv(
    path + 'customers.csv', 
    na_values=['Missing', 'Not Available', '-999', ' ']
)
display(df_clean.head())

,CustomerID,CustomerName,Gender,Age,Email,Phone,City,State,Country,Membership,SignupDate
0,107402,Priya Kulkarni,Male,32.0,priya.kulkarni77@gmail.com,9.709960e+09,Lucknow,Uttar Pradesh,India,Bronze,2021-05-05
1,105835,Ananya Banerjee,Male,47.0,ananya.banerjee593@yahoo.com,9.213418e+09,Chandigarh,Chandigarh,India,Bronze,2019-01-02
2,102123,Aarav Das,Male,48.0,aarav.das123@hotmail.com,9.310161e+09,Kochi,Kerala,India,Bronze,2020-08-03
3,108789,Diya Patel,Male,22.0,diya.patel68@hotmail.com,9.968083e+09,Lucknow,Uttar Pradesh,India,Platinum,2023-12-04
4,100305,Karan Yadav,Female,46.0,karan.yadav336@gmail.com,9.891291e+09,Jaipur,Rajasthan,India,Silver,2023-06-30

   Gender   Age  SignupDate
0    Male  32.0  2021-05-05
1    Male  47.0  2019-01-02
2    Male  48.0  2020-08-03
3    Male  22.0  2023-12-04
4  Female  46.0  2023-06-30

,CustomerID,CustomerName,Gender,Age,Email,Phone,City,State,Country,Membership,SignupDate
0,107402,Priya Kulkarni,Male,32.0,priya.kulkarni77@gmail.com,9.709960e+09,Lucknow,Uttar Pradesh,India,Bronze,2021-05-05
1,105835,Ananya Banerjee,Male,47.0,ananya.banerjee593@yahoo.com,9.213418e+09,Chandigarh,Chandigarh,India,Bronze,2019-01-02
2,102123,Aarav Das,Male,48.0,aarav.das123@hotmail.com,9.310161e+09,Kochi,Kerala,India,Bronze,2020-08-03
3,108789,Diya Patel,Male,22.0,diya.patel68@hotmail.com,9.968083e+09,Lucknow,Uttar Pradesh,India,Platinum,2023-12-04
4,100305,Karan Yadav,Female,46.0,karan.yadav336@gmail.com,9.891291e+09,Jaipur,Rajasthan,India,Silver,2023-06-30

Data type of 'date' column: datetime64[ns]

,CustomerName,Gender,Age,Email,Phone,City,State,Country,Membership,SignupDate
CustomerID,,,,,,,,,,
107402,Priya Kulkarni,Male,32.0,priya.kulkarni77@gmail.com,9.709960e+09,Lucknow,Uttar Pradesh,India,Bronze,2021-05-05
105835,Ananya Banerjee,Male,47.0,ananya.banerjee593@yahoo.com,9.213418e+09,Chandigarh,Chandigarh,India,Bronze,2019-01-02
102123,Aarav Das,Male,48.0,aarav.das123@hotmail.com,9.310161e+09,Kochi,Kerala,India,Bronze,2020-08-03
108789,Diya Patel,Male,22.0,diya.patel68@hotmail.com,9.968083e+09,Lucknow,Uttar Pradesh,India,Platinum,2023-12-04
100305,Karan Yadav,Female,46.0,karan.yadav336@gmail.com,9.891291e+09,Jaipur,Rajasthan,India,Silver,2023-06-30

,CustomerID,CustomerName,Gender,Age,Email,Phone,City,State,Country,Membership,SignupDate
0,107402,Priya Kulkarni,Male,32.0,priya.kulkarni77@gmail.com,9.709960e+09,Lucknow,Uttar Pradesh,India,Bronze,2021-05-05
1,105835,Ananya Banerjee,Male,47.0,ananya.banerjee593@yahoo.com,9.213418e+09,Chandigarh,Chandigarh,India,Bronze,2019-01-02
2,102123,Aarav Das,Male,48.0,aarav.das123@hotmail.com,9.310161e+09,Kochi,Kerala,India,Bronze,2020-08-03
3,108789,Diya Patel,Male,22.0,diya.patel68@hotmail.com,9.968083e+09,Lucknow,Uttar Pradesh,India,Platinum,2023-12-04
4,100305,Karan Yadav,Female,46.0,karan.yadav336@gmail.com,9.891291e+09,Jaipur,Rajasthan,India,Silver,2023-06-30

#### **10. How do you write a DataFrame to a CSV file?**
The `to_csv()` method exports your DataFrame back into a standard comma-separated text file. It gives you precise control over how row indices, column headers, and missing values are formatted on the disk.

In [10]:
import pandas as pd
import numpy as np

# Assume 'df' is the DataFrame you have been cleaning and processing
df = pd.DataFrame(
    {
        'City': ['Kolkata', 'Noida', 'Bengaluru', 'Hyderabad'],
        'AQI': ['100', '203', '147', '196'],
        'Status': ['Ok', 'Polluted', np.nan, 'Polluted'],
        'Population': [300000, 200000, np.nan, np.nan]
    }
)
# 1. Basic Export
# Writes the entire DataFrame to the current working directory.
# Note: By default, this saves the row index as the very first column in the CSV.
df.to_csv('processed_data.csv')

# 2. Export Without the Index (Most Common)
# Set index=False to prevent Pandas from writing the default numeric index (0, 1, 2...).
# This prevents an unnamed index column from appearing the next time you read the file.
df.to_csv('clean_data_no_index.csv', index=False)

# 3. Export Specific Columns
# Use the 'columns' parameter to save only a subset of your data.
df.to_csv(
    'subset_data.csv', 
    columns=['City', 'AQI', 'Status'], 
    index=False
)

# 4. Customizing Missing Data Representation
# 'na_rep' specifies how NaN values should appear in the text file. 
# By default, they are saved as empty strings. Here we replace them with 'NULL'.
df.to_csv(
    'data_with_nulls.csv', 
    index=False, 
    na_rep='NULL'
)

#### **11. How do you display the first few rows of a DataFrame?**
The `head()` method is used to quickly inspect the top rows of a DataFrame. This is an essential step immediately after loading data to verify the schema, column names, and data formats without printing thousands of rows to your screen.

In [11]:
import pandas as pd

# Creating a sample DataFrame with 6 rows
data = {
    'Station': ['Indiranagar', 'BTM Layout', 'HSR Layout', 'Koramangala', 'Whitefield', 'Jayanagar'],
    'AQI': [85, 112, 142, 110, 155, 92],
    'Status': ['Satisfactory', 'Poor', 'Very Poor', 'Poor', 'Very Poor', 'Satisfactory']
}
df = pd.DataFrame(data)

# 1. Default Usage
# By default, head() returns exactly the first 5 rows of the DataFrame
print("Default (First 5 rows):\n")
display(df.head())

# 2. Custom Row Count
# Pass an integer 'n' to view exactly that many rows from the top
print("\nFirst 3 rows:\n")
display(df.head(3))

# 3. Inspecting the Bottom Rows
# The tail() method works exactly like head(), but returns rows from the end of the dataset
# This is useful for checking if data appended correctly to the bottom of your file
print("\nLast 2 rows:\n")
display(df.tail(2))

Default (First 5 rows):

       Station  AQI        Status
0  Indiranagar   85  Satisfactory
1   BTM Layout  112          Poor
2   HSR Layout  142     Very Poor
3  Koramangala  110          Poor
4   Whitefield  155     Very Poor

First 3 rows:

       Station  AQI        Status
0  Indiranagar   85  Satisfactory
1   BTM Layout  112          Poor
2   HSR Layout  142     Very Poor

Last 2 rows:

      Station  AQI        Status
4  Whitefield  155     Very Poor
5   Jayanagar   92  Satisfactory

#### **12. How do you display the last few rows?**
The `tail()` method is the exact counterpart to `head()`, used to inspect the bottom rows of a DataFrame or Series. It is particularly useful for verifying the most recently appended data in chronological datasets or checking if summary/total rows were accidentally imported at the end of a CSV file.

In [12]:
import pandas as pd

# Creating a sample time-series DataFrame
data = {
    'Date': ['2026-09-07', '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11', '2026-09-12'],
    'Station': ['Kolkata Central'] * 6,
    'PM25_Level': [55.2, 58.1, 62.4, 70.1, 75.8, 80.2]
}
df = pd.DataFrame(data)

# 1. Default Usage
# By default, tail() returns exactly the last 5 rows of the DataFrame
print("Default (Last 5 rows):\n")
display(df.tail())

# 2. Custom Row Count
# Pass an integer 'n' to view exactly that many rows from the very bottom
print("\nLast 2 rows (Most recent data):\n")
display(df.tail(2))

# 3. Using tail() on a Single Column (Series)
# The method works identically on a 1D Series
print("\nLast 3 PM2.5 readings:\n")
print(df['PM25_Level'].tail(3))

Default (Last 5 rows):

         Date          Station  PM25_Level
1  2026-09-08  Kolkata Central        58.1
2  2026-09-09  Kolkata Central        62.4
3  2026-09-10  Kolkata Central        70.1
4  2026-09-11  Kolkata Central        75.8
5  2026-09-12  Kolkata Central        80.2

Last 2 rows (Most recent data):

         Date          Station  PM25_Level
4  2026-09-11  Kolkata Central        75.8
5  2026-09-12  Kolkata Central        80.2

Last 3 PM2.5 readings:

3    70.1
4    75.8
5    80.2
Name: PM25_Level, dtype: float64

#### **13. What does df.info() do?**
The `info()` method provides a concise structural summary of a DataFrame. It is the best diagnostic tool to run immediately after loading a dataset to check for missing values and ensure data types were parsed correctly.

**Key Diagnostic Information Provided**

* **Dimensions:** The total number of rows (index entries) and columns.
* **Data Types:** The `dtype` of each column (e.g., `int64`, `float64`, `object` for strings).
* **Non-Null Counts:** How many valid (non-missing) entries exist in each column, which instantly highlights where data is missing.
* **Memory Usage:** The RAM footprint of the DataFrame.

In [13]:
import pandas as pd
import numpy as np

# Creating a dataset with mixed types and missing values (NaN)
data = {
    'station_id': [101, 102, 103, 104],
    'city': ['Bengaluru', 'Kolkata', 'Chennai', 'Mumbai'],
    'pm25_level': [45.2, 55.1, np.nan, 80.2],  # Note the missing value here
    'is_active': [True, True, False, True]
}
df = pd.DataFrame(data)

# 1. Standard Info Summary
# Notice how 'pm25_level' will show 3 non-null out of 4 total rows
print("Standard df.info() Output:\n")
df.info()

# 2. Deep Memory Profiling
# By default, Pandas only estimates the memory of 'object' (string) columns. 
# Using memory_usage='deep' forces Pandas to inspect the exact memory footprint of all strings.
print("\nDeep Memory Profiling:\n")
df.info(memory_usage='deep')

Standard df.info() Output:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   station_id  4 non-null      int64
 1   city        4 non-null      object
 2   pm25_level  3 non-null      float64
 3   is_active   4 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 232.0+ bytes

Deep Memory Profiling:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   station_id  4 non-null      int64
 1   city        4 non-null      object
 2   pm25_level  3 non-null      float64
 3   is_active   4 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 425.0 bytes

#### **14. What does df.describe() return?**
The `describe()` method generates descriptive statistics that summarize the central tendency, dispersion, and shape of a dataset's distribution, automatically excluding `NaN` values. By default, it only profiles numeric columns (integers and floats), providing a rapid mathematical overview of your data.

**Numeric Output Metrics**
* **count:** Number of non-null observations.
* **mean:** The average value.
* **std:** Standard deviation (measure of data spread).
* **min / max:** The lowest and highest values.
* **25%, 50%, 75%:** The lower percentile, median (50%), and upper percentile.

In [14]:
import pandas as pd
import numpy as np

# Creating a dataset with both numeric and categorical data
data = {
    'station': ['Indiranagar', 'BTM Layout', 'HSR Layout', 'Koramangala', 'Whitefield'],
    'aqi': [85, 112, 142, 110, 155],
    'pm25_level': [45.2, 55.1, 70.4, np.nan, 82.5],
    'status': ['Satisfactory', 'Poor', 'Very Poor', 'Poor', 'Very Poor']
}
df = pd.DataFrame(data)

# 1. Default Behavior (Numeric Columns Only)
print("Numeric Statistics:\n")
display(df.describe())

# 2. Profiling Categorical/String Data
# Passing include='object' forces describe() to analyze string columns.
# It returns count, number of unique values, the most frequent value (top), 
# and its frequency (freq).
print("\nCategorical Statistics:\n")
display(df.describe(include=['object']))

# 3. Profiling All Columns
# Passing include='all' analyzes every column, filling cells with NaN 
# where a metric doesn't apply (e.g., 'mean' for a string column).
print("\nAll Columns Summary:\n")
display(df.describe(include='all'))

Numeric Statistics:

              aqi  pm25_level
count    5.000000    4.000000
mean   120.800000   63.300000
std     27.815463   16.471187
min     85.000000   45.200000
25%    110.000000   52.625000
50%    112.000000   62.750000
75%    142.000000   73.425000
max    155.000000   82.500000

Categorical Statistics:

            station status
count             5      5
unique            5      3
top     Indiranagar   Poor
freq              1      2

All Columns Summary:

            station         aqi  pm25_level status
count             5    5.000000    4.000000      5
unique            5         NaN         NaN      3
top     Indiranagar         NaN         NaN   Poor
freq              1         NaN         NaN      2
mean            NaN  120.800000   63.300000    NaN
std             NaN   27.815463   16.471187    NaN
min             NaN   85.000000   45.200000    NaN
25%             NaN  110.000000   52.625000    NaN
50%             NaN  112.000000   62.750000    NaN
75%             NaN  142.000000   73.425000    NaN
max             NaN  155.000000   82.500000    NaN

#### **15. How do you check the shape of a DataFrame?**
The `shape` attribute returns a tuple representing the dimensionality of the DataFrame in the format `(rows, columns)`. Because it is an underlying property of the DataFrame rather than a functional method, you do not use parentheses when calling it.

**Key Characteristics**
* **Zero-Indexed Tuple:** The first element `[0]` represents the total number of rows (index length), and the second element `[1]` represents the total number of columns.
* **Series Shape:** If called on a 1D Series, it returns a tuple with a single element: `(rows,)`.

In [15]:
import pandas as pd

# Creating a dataset with 4 rows and 3 columns
data = {
    'Station': ['BTM Layout', 'HSR Layout', 'Koramangala', 'Indiranagar'],
    'PM10_Level': [102.4, 89.1, 76.5, 95.0],
    'Status': ['Moderate', 'Satisfactory', 'Satisfactory', 'Moderate']
}
df = pd.DataFrame(data)

# 1. Getting the full shape tuple
dimensions = df.shape
print(f"Full Shape Tuple: {dimensions}")

# 2. Extracting rows and columns programmatically
# Useful when setting up loops or validating data sizes before machine learning pipelines
num_rows = df.shape[0]
num_cols = df.shape[1]

print(f"Total Rows: {num_rows}")
print(f"Total Columns: {num_cols}")

# 3. Checking the shape of a single column (Series)
series_shape = df['PM10_Level'].shape
print(f"Series Shape: {series_shape}")

Full Shape Tuple: (4, 3)
Total Rows: 4
Total Columns: 3
Series Shape: (4,)

#### **16. How do you list column names?**
The `columns` attribute returns the column labels of a DataFrame. Like `shape`, it is an attribute rather than a method, so you do not use parentheses. By default, it returns a pandas `Index` object, but it can easily be converted into a standard Python list.

**Key Characteristics**
* **Index Object:** The returned object is optimized for pandas operations but behaves similarly to a list.
* **Iterable:** You can easily loop through the `columns` attribute to apply bulk text formatting (like converting all names to lowercase).

In [16]:
import pandas as pd

# Creating a sample dataset
data = {
    'Station_ID': ['BTM', 'HSR', 'KOR'],
    'PM25_Level': [45.2, 55.1, 70.4],
    'Air_Quality_Index': [85, 112, 142]
}
df = pd.DataFrame(data)

# 1. Accessing the columns attribute directly
print("Raw Columns Index Object:")
print(df.columns)

# 2. Converting to a standard Python list (Most Common)
# Using .tolist() is the preferred way to extract headers for iteration or manipulation
col_list = df.columns.tolist()
print("\nAs a Python List:")
print(col_list)

# 3. Iterating through column names
# Useful for bulk renaming, such as converting all headers to lowercase
print("\nIterating through columns:")
for col in df.columns:
    print(f" - {col.lower()}")

# 4. Modifying column names directly
# You can overwrite the entire columns attribute by assigning a list of the exact same length
df.columns = ['station', 'pm25', 'aqi']
print("\nRenamed Columns:")
print(df.columns.tolist())

Raw Columns Index Object:
Index(['Station_ID', 'PM25_Level', 'Air_Quality_Index'], dtype='object')

As a Python List:
['Station_ID', 'PM25_Level', 'Air_Quality_Index']

Iterating through columns:
 - station_id
 - pm25_level
 - air_quality_index

Renamed Columns:
['station', 'pm25', 'aqi']

#### **17. How do you check data types of columns?**
The `dtypes` attribute returns a Series displaying the specific data type of each column in your DataFrame. Understanding these types is critical, as mathematical functions will fail on string columns, and date functions will fail if a date is stored as an `object` (string) instead of a `datetime` object.

**Common Pandas Data Types**
* **`int64` / `float64`:** Integer and floating-point numbers.
* **`object`:** Typically represents strings, but can also indicate a column containing mixed data types.
* **`bool`:** True/False boolean values.
* **`datetime64`:** Date and time values, which unlock time-series methods.

In [17]:
import pandas as pd

# Creating a dataset with a variety of data types
data = {
    'station_name': ['Bally', 'New Town', 'Salt Lake'], # object (string)
    'aqi': [110, 85, 92],                               # int64
    'pm25_level': [45.2, 38.1, 40.5],                   # float64
    'is_active': [True, True, False],                   # bool
    'last_calibrated': ['2026-08-01', '2026-08-15', '2026-09-01'] # object (currently a string)
}
df = pd.DataFrame(data)

# Convert the string column to actual datetime objects
df['last_calibrated'] = pd.to_datetime(df['last_calibrated'])

# 1. Checking all data types
# Returns a Pandas Series where the index is column names and values are the data types
print("Data types for all columns:\n")
print(df.dtypes)

# 2. Checking a single column's data type
print(f"\nData type of 'pm25_level': {df['pm25_level'].dtype}")

# 3. Filtering columns by data type
# select_dtypes() allows you to isolate columns for specific operations 
# (e.g., extracting only numeric columns before applying a scaling algorithm)
numeric_df = df.select_dtypes(include=['int64', 'float64'])
print("\nNumeric columns only:\n")
display(numeric_df)

# You can also use 'number' as a shortcut for all int/float types, 
# or use 'exclude' to drop certain types
text_only = df.select_dtypes(exclude=['number', 'bool', 'datetime64'])
print("\nText (object) columns only:\n")
display(text_only)

Data types for all columns:

station_name               object
aqi                         int64
pm25_level                float64
is_active                    bool
last_calibrated    datetime64[ns]
dtype: object

Data type of 'pm25_level': float64

Numeric columns only:

   aqi  pm25_level
0  110        45.2
1   85        38.1
2   92        40.5

Text (object) columns only:

  station_name
0        Bally
1     New Town
2    Salt Lake

#### **18. How do you rename columns?**
You can rename columns in Pandas by either mapping specific column names using a dictionary or by completely overwriting the column index array.

**Common Renaming Methods**
* **The `rename()` Method:** The safest approach. It uses a dictionary to target specific columns, leaving unspecified columns untouched regardless of their order.
* **Index Assignment:** Overwrites the entire `df.columns` attribute at once. It is fast but requires providing a list that exactly matches the total number of columns.
* **Vectorized String Operations:** Applies string methods (like lowercase or replace) across the entire column index simultaneously, which is ideal for cleaning messy, inconsistent headers.

In [18]:
import pandas as pd

# Creating a sample dataset with messy, capitalized column names containing spaces
data = {
    'Station Name': ['Salt Lake', 'New Town'],
    'PM2.5': [45.2, 38.1],
    'AQI Level': [92, 85]
}
df = pd.DataFrame(data)
print("Original Columns:", df.columns.tolist())

# 1. Using rename() with a Dictionary (Targeted approach)
# Keys are the old names, values are the new names.
# This returns a new DataFrame unless you pass inplace=True.
df_renamed = df.rename(columns={
    'Station Name': 'station', 
    'PM2.5': 'pm25'
})
print("\nTargeted Rename:")
display(df_renamed)

# 2. Overwriting the columns attribute (Complete replacement)
# The provided list must match the exact number of columns in the DataFrame.
df.columns = ['station_id', 'pm25_reading', 'aqi_score']
print("\nFull Overwrite:")
display(df)

# 3. Bulk Vectorized String Operations (Automated cleanup)
# Ideal for standardizing hundreds of columns without typing them out manually.
df_raw = pd.DataFrame(data)

# Convert all headers to lowercase, replace spaces with underscores, and remove periods
df_raw.columns = (
    df_raw.columns
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('.', '')
)

print("\nAutomated String Cleanup:")
display(df_raw)

Original Columns: ['Station Name', 'PM2.5', 'AQI Level']

Targeted Rename:

     station  pm25  AQI Level
0  Salt Lake  45.2         92
1   New Town  38.1         85

Full Overwrite:

  station_id  pm25_reading  aqi_score
0  Salt Lake          45.2         92
1   New Town          38.1         85

Automated String Cleanup:

  station_name  pm25  aqi_level
0    Salt Lake  45.2         92
1     New Town  38.1         85

#### **19. How do you select a single column?**
You can select a single column from a DataFrame using either bracket notation or dot notation. Both methods extract the column and return it as a 1-Dimensional Pandas Series.

**Selection Methods**
* **Bracket Notation (`df['Column Name']`):** The safest and most universally recommended method. It successfully handles column names that contain spaces, special characters, or names that conflict with built-in Pandas methods.
* **Dot Notation (`df.Column_Name`):** A faster shorthand commonly used in exploratory analysis. However, it *only* works if the column name is a valid Python variable (no spaces) and does not conflict with existing Pandas methods (like `min`, `shape`, or `count`).

In [19]:
import pandas as pd

# Creating a dataset with a mix of safe and complex column names
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake'],
    'aqi': [115, 85, 92],
    'PM 2.5 Level': [48.2, 38.1, 40.5], # Contains spaces and special characters
    'count': [1, 2, 3]                  # Conflicts with the DataFrame.count() method
}
df = pd.DataFrame(data)

# 1. Bracket Notation (Recommended)
# Works perfectly for any string
aqi_series = df['aqi']
print("Bracket Notation Output:\n", aqi_series)

# 2. Dot Notation (Convenience)
# Works only for valid variable names without spaces
station_series = df.station
print("\nDot Notation Output:\n", station_series)

# 3. Handling Complex Names
# df.PM 2.5 Level would throw a SyntaxError. You MUST use brackets here.
pm_series = df['PM 2.5 Level']

# 4. Method Conflicts
# df.count returns the built-in counting method, NOT your data column.
# To get your actual data column named 'count', you must use brackets.
actual_count_data = df['count']

# 5. Verifying the Object Type
# Extracting a single column always returns a Series
print(f"\nType of extracted column: {type(aqi_series)}")

Bracket Notation Output:
 0    115
1     85
2     92
Name: aqi, dtype: int64

Dot Notation Output:
 0       Howrah
1     New Town
2    Salt Lake
Name: station, dtype: object

Type of extracted column: <class 'pandas.core.series.Series'>

#### **20. How do you select multiple columns?**
You can select multiple columns by passing a Python list of column names inside the standard DataFrame indexing brackets. This creates a "double bracket" syntax `df[['col1', 'col2']]` and always returns a new DataFrame rather than a Series.

**Key Characteristics**
* **Double Brackets:** The outer brackets represent the indexing operation, while the inner brackets contain the Python list of column strings.
* **Output Type:** Because you are extracting multiple dimensions, the result is always a 2-Dimensional DataFrame.
* **Column Reordering:** The columns in the new DataFrame will appear in the exact order you specify in your list, which provides a fast way to reorder your dataset on the fly.

In [20]:
import pandas as pd

# Creating a sample dataset
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake'],
    'aqi': [115, 85, 92],
    'pm25_level': [48.2, 38.1, 40.5],
    'temperature_c': [31, 32, 30]
}
df = pd.DataFrame(data)

# 1. Standard Multiple Selection (Double Brackets)
# Pass a list of column names directly into the indexing brackets
subset_df = df[['station', 'aqi']]
print("Multiple Column Extraction:\n")
display(subset_df)

# 2. Using a Variable List
# This approach is much cleaner when extracting many columns or dynamically generating the list
target_columns = ['station', 'temperature_c', 'pm25_level']
reordered_df = df[target_columns]

print("\nExtraction Using a List Variable (Note the new column order):\n")
display(reordered_df)

# 3. Verifying the Object Type
print(f"\nType of multiple extracted columns: {type(subset_df)}")

# 4. Forcing a Single Column into a DataFrame
# If you use double brackets on a single column name, Pandas returns a 2D DataFrame 
# instead of a 1D Series. This is often required when feeding single features into Scikit-Learn.
single_col_df = df[['aqi']]
print(f"Type of single column with double brackets: {type(single_col_df)}")

Multiple Column Extraction:

     station  aqi
0     Howrah  115
1   New Town   85
2  Salt Lake   92

Extraction Using a List Variable (Note the new column order):

     station  temperature_c  pm25_level
0     Howrah             31        48.2
1   New Town             32        38.1
2  Salt Lake             30        40.5

Type of multiple extracted columns: <class 'pandas.core.frame.DataFrame'>
Type of single column with double brackets: <class 'pandas.core.frame.DataFrame'>

## Intermediate Level (21–50)

#### **21. What is the difference between loc[] and iloc[]?**
The fundamental difference between `loc[]` and `iloc[]` is how they locate data: **`loc[]` uses explicit labels (names)**, while **`iloc[]` uses implicit integer positions (0-based indexing)**.

Both methods accept two arguments in the format `[rows, columns]`, but they process those arguments very differently.

**Key Behavioral Differences**  
| Feature | `loc[]` (Label-Based) | `iloc[]` (Integer-Based) |
| --- | --- | --- |
| **Lookup Mechanism** | Looks for the actual name/label of the row index and column header. | Looks for the exact numerical row and column position (0, 1, 2...). |
| **Slicing Bounds** | Both the start and stop bounds are **INCLUSIVE**. | The stop bound is **EXCLUSIVE** (matches standard Python list behavior). |
| **Valid Inputs** | Strings, lists of strings, boolean arrays, or a slice object with labels (`'A':'C'`). | Integers, lists of integers, boolean arrays, or a slice object with integers (`0:3`). |

In [21]:
import pandas as pd

# Creating a dataset with custom row index labels (not standard 0,1,2..)
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake', 'Bally', 'Park Street'],
    'aqi': [115, 85, 92, 110, 105],
    'pm25': [48.2, 38.1, 40.5, 45.0, 42.1]
}
# Setting letters as the row index to clearly distinguish label from position
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
display(df)

print("\n1. Single Row Selection")
# loc looks for the label 'b'
print("loc['b']:\n", df.loc['b'].to_frame().T)
# iloc looks for the integer position 1 (which happens to be row 'b')
print("\niloc[1]:\n", df.iloc[1].to_frame().T)

print("\n2. Selecting Rows and Columns")
# loc uses the column name string
print("loc['c', 'aqi']:", df.loc['c', 'aqi'])
# iloc uses the column integer position (aqi is at index 1)
print("iloc[2, 1]:", df.iloc[2, 1])

print("\n3. Slicing Behavior (Crucial Difference)")
# loc includes the final element 'c'
print("loc['a':'c'] (INCLUSIVE of 'c'):\n")
display(df.loc['a':'c', ['station', 'aqi']])

# iloc excludes the final index 2 (stops at 1)
print("\niloc[0:2] (EXCLUSIVE of index 2):\n")
display(df.iloc[0:2, 0:2])

       station  aqi  pm25
a       Howrah  115  48.2
b     New Town   85  38.1
c    Salt Lake   92  40.5
d        Bally  110  45.0
e  Park Street  105  42.1

1. Single Row Selection
loc['b']:
     station aqi  pm25
b  New Town  85  38.1

iloc[1]:
     station aqi  pm25
b  New Town  85  38.1

2. Selecting Rows and Columns
loc['c', 'aqi']: 92
iloc[2, 1]: 92

3. Slicing Behavior (Crucial Difference)
loc['a':'c'] (INCLUSIVE of 'c'):

     station  aqi
a     Howrah  115
b   New Town   85
c  Salt Lake   92

iloc[0:2] (EXCLUSIVE of index 2):

    station  aqi
a    Howrah  115
b  New Town   85

#### **22. What is label-based indexing?**
Label-based indexing is a method of extracting data from a DataFrame or Series using the explicit names (labels) assigned to rows and columns, rather than their underlying numerical positions. In Pandas, this operation is executed exclusively using the `.loc[]` indexer.

**Key Characteristics of `.loc[]`**  
* **Explicit Naming:** It strictly searches for the actual row index label (which could be a string, a date, or an integer) and the exact column header string.
* **Inclusive Slicing:** When slicing data (e.g., `loc['A':'C']`), Pandas includes both the start bound and the stop bound. This is a major departure from standard Python list slicing.
* **Boolean Masking:** It natively accepts boolean arrays, making it the primary method for conditional data filtering.

In [22]:
import pandas as pd

# Creating a dataset and setting explicit string labels as the row index
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake', 'Bally'],
    'aqi': [115, 85, 92, 110],
    'pm25_level': [48.2, 38.1, 40.5, 45.0]
}
# Assigning custom row labels instead of the default 0, 1, 2, 3
df = pd.DataFrame(data, index=['Day_1', 'Day_2', 'Day_3', 'Day_4'])
print("Original Labeled DataFrame:")
display(df)

# 1. Selecting a single row by its label
# Returns a Series where the column names become the index
day2_data = df.loc['Day_2']
print("\nSingle Row (Day_2):\n", day2_data)

# 2. Selecting specific rows and specific columns
# Syntax: df.loc[[row_labels], [column_labels]]
subset = df.loc[['Day_1', 'Day_3'], ['station', 'aqi']]
print("\nSpecific Rows and Columns:")
display(subset)

# 3. Slicing with labels (INCLUSIVE of the end bound)
# Extracts everything from Day_2 through Day_4, including Day_4
slice_df = df.loc['Day_2':'Day_4', 'aqi':'pm25_level']
print("\nInclusive Slicing:")
display(slice_df)

# 4. Conditional Filtering (Boolean Indexing)
# Extract all columns where the AQI is greater than 100
high_pollution = df.loc[df['aqi'] > 100, ['station', 'aqi']]
print("\nConditional Filtering with loc:")
display(high_pollution)

Original Labeled DataFrame:

         station  aqi  pm25_level
Day_1     Howrah  115        48.2
Day_2   New Town   85        38.1
Day_3  Salt Lake   92        40.5
Day_4      Bally  110        45.0

Single Row (Day_2):
 station       New Town
aqi                 85
pm25_level        38.1
Name: Day_2, dtype: object

Specific Rows and Columns:

         station  aqi
Day_1     Howrah  115
Day_3  Salt Lake   92

Inclusive Slicing:

       aqi  pm25_level
Day_2   85        38.1
Day_3   92        40.5
Day_4  110        45.0

Conditional Filtering with loc:

      station  aqi
Day_1  Howrah  115
Day_4   Bally  110

#### **23. What is integer-based indexing?**
Integer-based indexing is a method of extracting data based solely on its 0-based numerical position in the DataFrame, completely ignoring any custom row labels or column names. In Pandas, this operation is executed exclusively using the `.iloc[]` indexer.

**Key Characteristics of `.iloc[]`**  
* **Positional Targeting:** It operates exactly like standard Python lists or NumPy arrays. The first row and first column are always at index `0`.
* **Exclusive Slicing:** When slicing data (e.g., `iloc[0:3]`), Pandas extracts rows 0, 1, and 2, but strictly excludes the stop bound (index 3).
* **Negative Indexing:** It natively supports negative integers, allowing you to easily grab the last row (`iloc[-1]`) or last column without needing to know the exact length of the dataset.

In [23]:
import pandas as pd

# Creating a dataset and setting explicit string labels
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake', 'Bally'],
    'aqi': [115, 85, 92, 110],
    'pm25_level': [48.2, 38.1, 40.5, 45.0]
}
df = pd.DataFrame(data, index=['Day_1', 'Day_2', 'Day_3', 'Day_4'])
print("Original Labeled DataFrame:")
display(df)

# 1. Selecting a single row by position
# Extracts the second row (index 1), ignoring the label 'Day_2'
row_one = df.iloc[1]
print("\nRow at index 1:\n", row_one)

# 2. Selecting specific rows and columns by position
# Syntax: df.iloc[[row_indices], [column_indices]]
# Extracts the 1st and 3rd rows, and the 1st and 2nd columns
subset = df.iloc[[0, 2], [0, 1]]
print("\nSpecific Row/Col Positions:")
display(subset)

# 3. Slicing with integers (EXCLUSIVE of the end bound)
# Extracts rows 1 and 2, and columns 1 and 2
slice_df = df.iloc[1:3, 1:3]
print("\nExclusive Slicing (Rows 1:3, Cols 1:3):")
display(slice_df)

# 4. Negative Indexing
# Extracts the very last row and the last two columns
last_row_data = df.iloc[-1, -2:]
print("\nNegative Indexing (Last Row, Last 2 Cols):\n", last_row_data)

Original Labeled DataFrame:

         station  aqi  pm25_level
Day_1     Howrah  115        48.2
Day_2   New Town   85        38.1
Day_3  Salt Lake   92        40.5
Day_4      Bally  110        45.0

Row at index 1:
 station       New Town
aqi                 85
pm25_level        38.1
Name: Day_2, dtype: object

Specific Row/Col Positions:

         station  aqi
Day_1     Howrah  115
Day_3  Salt Lake   92

Exclusive Slicing (Rows 1:3, Cols 1:3):

       aqi  pm25_level
Day_2   85        38.1
Day_3   92        40.5

Negative Indexing (Last Row, Last 2 Cols):
 aqi            110
pm25_level    45.0
Name: Day_4, dtype: object

#### **24. How do you filter rows based on conditions?**
Filtering rows relies on a technique called **boolean masking**. You create a condition that evaluates every row as `True` or `False`, and Pandas returns a new DataFrame containing only the rows where the condition evaluated to `True`.

**Key Filtering Rules**  
* **Bitwise Operators:** You cannot use standard Python logical operators (`and`, `or`, `not`). You must use bitwise operators: `&` (AND), `|` (OR), and `~` (NOT).
* **Mandatory Parentheses:** When chaining multiple conditions, wrap each individual condition in parentheses `()` to dictate the order of operations, otherwise Pandas will throw an error.
* **The `.isin()` Method:** A cleaner alternative to writing multiple `|` (OR) statements when checking if a column value matches any item in a list.

In [24]:
import pandas as pd

# Creating a sample dataset
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake', 'Bally', 'Park Street'],
    'aqi': [115, 85, 92, 160, 105],
    'status': ['Poor', 'Good', 'Satisfactory', 'Very Poor', 'Poor']
}
df = pd.DataFrame(data)

# 1. Single Condition Filtering
# Extract all rows where the AQI is strictly greater than 100
high_aqi = df[df['aqi'] > 100]
print("Single Condition (AQI > 100):")
display(high_aqi)

# 2. Multiple Conditions using AND (&)
# Both conditions must be True. Notice the mandatory parentheses.
moderate_risk = df[(df['aqi'] > 90) & (df['aqi'] < 120)]
print("\nMultiple Conditions AND:")
display(moderate_risk)

# 3. Multiple Conditions using OR (|)
# Only one condition needs to be True.
extreme_cases = df[(df['aqi'] < 90) | (df['status'] == 'Very Poor')]
print("\nMultiple Conditions OR:")
display(extreme_cases)

# 4. Using the .isin() Method
# Checks if the column value exists within a provided list. 
# Much cleaner than writing: (df['station'] == 'Howrah') | (df['station'] == 'Bally')
target_stations = ['Howrah', 'Bally']
specific_locations = df[df['station'].isin(target_stations)]
print("\nUsing .isin() for Lists:")
display(specific_locations)

# 5. Using String Methods for Filtering
# Extracts rows where the status text contains the word 'Poor'
poor_conditions = df[df['status'].str.contains('Poor')]
print("\nString Method Filtering:")
display(poor_conditions)

Single Condition (AQI > 100):

       station  aqi     status
0       Howrah  115       Poor
3        Bally  160  Very Poor
4  Park Street  105       Poor

Multiple Conditions AND:

       station  aqi        status
0       Howrah  115          Poor
2    Salt Lake   92  Satisfactory
4  Park Street  105          Poor

Multiple Conditions OR:

    station  aqi     status
1  New Town   85       Good
3     Bally  160  Very Poor

Using .isin() for Lists:

  station  aqi     status
0  Howrah  115       Poor
3   Bally  160  Very Poor

String Method Filtering:

       station  aqi     status
0       Howrah  115       Poor
3        Bally  160  Very Poor
4  Park Street  105       Poor

#### **25. How do you select rows with multiple conditions?**
Selecting rows based on multiple conditions requires combining individual boolean masks using bitwise operators.

Standard Python logical operators (`and`, `or`, `not`) will throw a `ValueError` because they attempt to evaluate the entire DataFrame's truth value at once. You must use element-wise operators instead, and **you must wrap every individual condition in parentheses `()`** due to Python's operator precedence rules.

**Key Operators for Multiple Conditions**  
* **`&` (AND):** The row is selected only if *all* conditions are True.
* **`|` (OR):** The row is selected if *at least one* condition is True.
* **`~` (NOT):** Reverses the condition (True becomes False).
* **`.query()`:** An elegant, string-based alternative method that often makes complex multi-condition filters much easier to read.

In [25]:
import pandas as pd

# Creating a dataset with multiple numerical and categorical columns
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake', 'Bally', 'Park Street'],
    'aqi': [115, 85, 92, 160, 105],
    'pm25': [48.2, 35.1, 39.5, 65.0, 42.1],
    'is_active': [True, True, False, True, True]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Multiple Conditions with AND (&)
# Both conditions must be True. (Notice the parentheses!)
high_and_active = df[(df['aqi'] > 100) & (df['is_active'] == True)]
print("\nStations with AQI > 100 AND are Active:")
display(high_and_active)

# 2. Multiple Conditions with OR (|)
# Only one condition needs to be True.
extreme_or_inactive = df[(df['aqi'] >= 150) | (df['is_active'] == False)]
print("\nStations with AQI >= 150 OR are Inactive:")
display(extreme_or_inactive)

# 3. Combining AND, OR, and NOT (~)
# Select stations that are active, AND (AQI is < 90 OR PM2.5 is < 40)
complex_filter = df[~df['is_active'] == False & ((df['aqi'] < 90) | (df['pm25'] < 40))]
print("\nComplex Filter Using Multiple Operators:")
display(complex_filter)

# 4. The .query() Method (Cleaner Syntax Alternative)
# You can write the entire logic as a string. It allows the use of 'and' / 'or' keywords.
# Note: It requires variable names to be valid Python identifiers (no spaces).
query_result = df.query("aqi > 100 and is_active == True")
print("\nUsing .query() for cleaner syntax:")
display(query_result)

Original Dataset:

       station  aqi  pm25  is_active
0       Howrah  115  48.2       True
1     New Town   85  35.1       True
2    Salt Lake   92  39.5      False
3        Bally  160  65.0       True
4  Park Street  105  42.1       True

Stations with AQI > 100 AND are Active:

       station  aqi  pm25  is_active
0       Howrah  115  48.2       True
3        Bally  160  65.0       True
4  Park Street  105  42.1       True

Stations with AQI >= 150 OR are Inactive:

     station  aqi  pm25  is_active
2  Salt Lake   92  39.5      False
3      Bally  160  65.0       True

Complex Filter Using Multiple Operators:

       station  aqi  pm25  is_active
0       Howrah  115  48.2       True
1     New Town   85  35.1       True
3        Bally  160  65.0       True
4  Park Street  105  42.1       True

Using .query() for cleaner syntax:

       station  aqi  pm25  is_active
0       Howrah  115  48.2       True
3        Bally  160  65.0       True
4  Park Street  105  42.1       True

#### **26. What is boolean indexing?**
Boolean indexing is the process of selecting subsets of data based on their actual values rather than their row labels or integer positions. It relies on a "boolean mask"—a sequence of `True` and `False` values that perfectly aligns with the rows of your dataset.

When you pass this mask into a DataFrame or Series, Pandas acts like a sieve: it keeps every row corresponding to `True` and drops every row corresponding to `False`.

**Key Characteristics**  
* **The Mask:** A boolean mask is simply a Pandas Series containing only boolean data types (`bool`).
* **Dynamic Generation:** In practice, you rarely type out `True` and `False` manually. Instead, you generate the mask dynamically by applying a logical condition to a column (e.g., `df['AQI'] > 100`).
* **Alignment:** The mask must have the exact same number of rows as the DataFrame you are filtering, or Pandas will throw an error.

In [26]:
import pandas as pd

# Creating a sample dataset
data = {
    'station': ['Howrah', 'New Town', 'Salt Lake', 'Bally'],
    'aqi': [115, 85, 92, 160]
}
df = pd.DataFrame(data)
print("Original Dataset:\n")
display(df)

# 1. The Manual Boolean Mask
# Passing an explicit list of True/False values of the exact same length as the DataFrame
manual_mask = [True, False, False, True]
explicit_filter = df[manual_mask]

print("\nFiltering with a Manual Mask (Keeps rows 0 and 3):")
display(explicit_filter)

# 2. The Dynamic Boolean Mask
# This is what happens under the hood when you write a condition.
# It evaluates the column and returns a Series of True/False values.
dynamic_mask = df['aqi'] > 100
print("\nThe Generated Boolean Series:")
print(dynamic_mask)
print(f"\nData Type of the mask: {dynamic_mask.dtype}")

# 3. Applying the Dynamic Mask
# We pass the generated Series into the DataFrame brackets
# This is the exact equivalent of: df[df['aqi'] > 100]
applied_filter = df[dynamic_mask]

print("\nFiltering with the Dynamic Mask:")
display(applied_filter)

Original Dataset:

     station  aqi
0     Howrah  115
1   New Town   85
2  Salt Lake   92
3      Bally  160

Filtering with a Manual Mask (Keeps rows 0 and 3):

  station  aqi
0  Howrah  115
3   Bally  160

The Generated Boolean Series:
0     True
1    False
2    False
3     True
Name: aqi, dtype: bool

Data Type of the mask: bool

Filtering with the Dynamic Mask:

  station  aqi
0  Howrah  115
3   Bally  160

#### **27. How do you sort a DataFrame?**
You can sort a DataFrame in Pandas using two primary methods: `sort_values()` to sort by the actual data within columns, and `sort_index()` to sort by the row labels.

By default, Pandas returns a completely new, sorted DataFrame and leaves your original dataset unchanged, unless you explicitly pass the parameter `inplace=True`.

**Key Sorting Parameters**  
* **`by`:** The column name (or list of column names) to sort by.
* **`ascending`:** A boolean (or list of booleans) dictating the sort order. Defaults to `True` (A-Z, 0-9).
* **`na_position`:** Dictates where missing values (`NaN`) should end up. Defaults to `'last'`, but can be changed to `'first'`.

In [27]:
import pandas as pd
import numpy as np

# Creating a dataset with a tie in AQI and a missing value
data = {
    'station': ['Salt Lake', 'New Town', 'Bally', 'Howrah', 'Park Street'],
    'aqi': [92, 85, 110, 110, np.nan],
    'pm25_level': [40.5, 38.1, 45.0, 48.2, 42.1]
}
# Using a custom index out of alphabetical order
df = pd.DataFrame(data, index=['C', 'A', 'E', 'B', 'D'])
print("Original Dataset:")
display(df)

# 1. Sorting by a single column (Default: Ascending)
# Notice how the NaN value is automatically pushed to the very bottom
sort_single = df.sort_values(by='aqi')
print("\nSorted by AQI (Ascending):")
display(sort_single)

# 2. Sorting in Descending Order
sort_desc = df.sort_values(by='aqi', ascending=False)
print("\nSorted by AQI (Descending):")
display(sort_desc)

# 3. Sorting by Multiple Columns (Tie-Breaking)
# If the AQIs are tied (like Bally and Howrah), it looks at the pm25_level.
# We can pass a list of booleans to sort AQI ascending, but PM2.5 descending.
sort_multi = df.sort_values(
    by=['aqi', 'pm25_level'], 
    ascending=[True, False]
)
print("\nSorted by Multiple Columns (AQI Asc, PM2.5 Desc):")
display(sort_multi)

# 4. Controlling Missing Values
# Force NaN values to appear at the top of the dataset instead of the bottom
sort_nan = df.sort_values(by='aqi', na_position='first')
print("\nSorted by AQI with NaNs First:")
display(sort_nan)

# 5. Sorting by the Index
# Reorders the DataFrame based on the row labels ('A', 'B', 'C'...) rather than the data
sort_idx = df.sort_index()
print("\nSorted Alphabetically by Row Index:")
display(sort_idx)

Original Dataset:

       station    aqi  pm25_level
C    Salt Lake   92.0        40.5
A     New Town   85.0        38.1
E        Bally  110.0        45.0
B       Howrah  110.0        48.2
D  Park Street    NaN        42.1

Sorted by AQI (Ascending):

       station    aqi  pm25_level
A     New Town   85.0        38.1
C    Salt Lake   92.0        40.5
E        Bally  110.0        45.0
B       Howrah  110.0        48.2
D  Park Street    NaN        42.1

Sorted by AQI (Descending):

       station    aqi  pm25_level
E        Bally  110.0        45.0
B       Howrah  110.0        48.2
C    Salt Lake   92.0        40.5
A     New Town   85.0        38.1
D  Park Street    NaN        42.1

Sorted by Multiple Columns (AQI Asc, PM2.5 Desc):

       station    aqi  pm25_level
A     New Town   85.0        38.1
C    Salt Lake   92.0        40.5
B       Howrah  110.0        48.2
E        Bally  110.0        45.0
D  Park Street    NaN        42.1

Sorted by AQI with NaNs First:

       station    aqi  pm25_level
D  Park Street    NaN        42.1
A     New Town   85.0        38.1
C    Salt Lake   92.0        40.5
E        Bally  110.0        45.0
B       Howrah  110.0        48.2

Sorted Alphabetically by Row Index:

       station    aqi  pm25_level
A     New Town   85.0        38.1
B       Howrah  110.0        48.2
C    Salt Lake   92.0        40.5
D  Park Street    NaN        42.1
E        Bally  110.0        45.0

#### **28. What is the difference between sort_values() and sort_index()?**
The fundamental difference is what they use as the sorting key: `sort_values()` evaluates the actual data stored *inside* your columns, whereas `sort_index()` evaluates the structural labels assigned to your rows (or columns).

| Feature | `sort_values()` | `sort_index()` |
| --- | --- | --- |
| **Sorting Target** | The actual values within one or more columns (e.g., finding the highest AQI). | The structural row labels (e.g., ordering by date or alphabetical ID). |
| **Required Parameters** | Requires the `by` parameter to know which column(s) to evaluate. | Does not require a `by` parameter; it automatically defaults to the row index. |
| **Common Use Case** | Ranking data (top performers, lowest errors, alphabetical grouping). | Restoring chronological order after a groupby operation or shuffling data. |

In [28]:
import pandas as pd

# Creating a dataset with a scrambled chronological index and scrambled data
data = {
    'station': ['New Town', 'Bally', 'Salt Lake', 'Howrah'],
    'aqi': [85, 110, 92, 115]
}
# The index represents dates, but they are out of order
df = pd.DataFrame(data, index=['2026-09-12', '2026-09-10', '2026-09-13', '2026-09-11'])
print("Original Scrambled Dataset:")
display(df)

# 1. Using sort_values()
# Ignores the dates completely and ranks the dataset from lowest to highest AQI
value_sorted = df.sort_values(by='aqi')
print("\nsort_values(by='aqi') - Ranked by Pollution Level:")
display(value_sorted)

# 2. Using sort_index()
# Ignores the AQI data completely and restores chronological order based on the row labels
index_sorted = df.sort_index()
print("\nsort_index() - Restored to Chronological Order:")
display(index_sorted)

# 3. sorting columns using sort_index
# sort_index can also sort the column headers alphabetically if you change the axis
col_sorted = df.sort_index(axis=1)
print("\nsort_index(axis=1) - Columns sorted alphabetically (aqi, station):")
display(col_sorted)

Original Scrambled Dataset:

              station  aqi
2026-09-12   New Town   85
2026-09-10      Bally  110
2026-09-13  Salt Lake   92
2026-09-11     Howrah  115

sort_values(by='aqi') - Ranked by Pollution Level:

              station  aqi
2026-09-12   New Town   85
2026-09-13  Salt Lake   92
2026-09-10      Bally  110
2026-09-11     Howrah  115

sort_index() - Restored to Chronological Order:

              station  aqi
2026-09-10      Bally  110
2026-09-11     Howrah  115
2026-09-12   New Town   85
2026-09-13  Salt Lake   92

sort_index(axis=1) - Columns sorted alphabetically (aqi, station):

            aqi    station
2026-09-12   85   New Town
2026-09-10  110      Bally
2026-09-13   92  Salt Lake
2026-09-11  115     Howrah

#### **29. How do you remove duplicate rows?**
The `drop_duplicates()` method scans your DataFrame for identical rows and removes them. By default, it evaluates every single column to find exact row-to-row matches and keeps only the first occurrence it encounters.

**Key Parameters for Precision Control**  
* **`subset`:** A column name or list of columns. Instead of requiring the entire row to be identical, Pandas will only look for duplicates within these specific columns.
* **`keep`:** Dictates which version of the duplicate to retain.
    * `'first'` (Default): Keeps the initial occurrence.
    * `'last'`: Keeps the final occurrence (useful if the last row is the most recent update).
    * `False`: Drops *all* rows that have duplicates, keeping only truly unique records.
* **`inplace`:** Set to `True` to overwrite your existing DataFrame instead of creating a new one.

In [29]:
import pandas as pd

# Creating a dataset with exact duplicates and partial duplicates
data = {
    'station': ['Salt Lake', 'New Town', 'Salt Lake', 'Bally', 'New Town'],
    'date': ['2026-09-10', '2026-09-10', '2026-09-10', '2026-09-11', '2026-09-10'],
    'aqi': [92, 85, 92, 110, 88] 
    # Row 0 and Row 2 are EXACT duplicates.
    # Row 1 and Row 4 share the same station and date, but have different AQIs.
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Default Behavior (Exact row matches only)
# Removes Row 2 because it is completely identical to Row 0.
exact_deduped = df.drop_duplicates()
print("\nDefault Drop (Keeps first exact match):")
display(exact_deduped)

# 2. Using 'subset' to define what constitutes a duplicate
# Even though the AQI is different, we consider it a duplicate if the 
# station and date are the same.
subset_deduped = df.drop_duplicates(subset=['station', 'date'])
print("\nSubset Drop (Checks only station and date):")
display(subset_deduped)

# 3. Changing the 'keep' parameter
# Drops the first occurrence of the New Town duplicate and keeps the last one (Row 4)
keep_last = df.drop_duplicates(subset=['station', 'date'], keep='last')
print("\nKeep Last Occurrence:")
display(keep_last)

# 4. Dropping ALL duplicates
# Removes any record that appears more than once based on the subset.
# Salt Lake and New Town are completely removed. Only Bally remains.
drop_all = df.drop_duplicates(subset=['station', 'date'], keep=False)
print("\nDrop All Duplicates (Keep only unique records):")
display(drop_all)

Original Dataset:

     station        date  aqi
0  Salt Lake  2026-09-10   92
1   New Town  2026-09-10   85
2  Salt Lake  2026-09-10   92
3      Bally  2026-09-11  110
4   New Town  2026-09-10   88

Default Drop (Keeps first exact match):

     station        date  aqi
0  Salt Lake  2026-09-10   92
1   New Town  2026-09-10   85
3      Bally  2026-09-11  110
4   New Town  2026-09-10   88

Subset Drop (Checks only station and date):

     station        date  aqi
0  Salt Lake  2026-09-10   92
1   New Town  2026-09-10   85
3      Bally  2026-09-11  110

Keep Last Occurrence:

     station        date  aqi
2  Salt Lake  2026-09-10   92
3      Bally  2026-09-11  110
4   New Town  2026-09-10   88

Drop All Duplicates (Keep only unique records):

  station        date  aqi
3   Bally  2026-09-11  110

#### **30. How do you count duplicates?**
You can count the total number of duplicate rows in a DataFrame by chaining the `duplicated()` method with the `sum()` function.

The `duplicated()` method returns a boolean mask—a Series of `True` and `False` values indicating whether each row is a duplicate. Because Python evaluates `True` as `1` and `False` as `0`, summing this boolean mask yields the exact integer count of duplicate records.

**Common Duplicate Counting Techniques**  
* **Total Count (`df.duplicated().sum()`):** Returns a single integer representing how many exact row matches exist.
* **Subset Count:** Passing the `subset` parameter counts duplicates based only on specific columns (e.g., finding multiple readings for the same station on the same day).
* **Frequency Breakdown (`value_counts()`):** While `duplicated().sum()` gives you a single grand total, `value_counts()` allows you to see exactly *which* rows are duplicated and how many times each one appears.

In [30]:
import pandas as pd

# Creating a dataset with exact duplicates and partial duplicates
data = {
    'station': ['Salt Lake', 'New Town', 'Salt Lake', 'Bally', 'New Town', 'New Town'],
    'date': ['2026-09-10', '2026-09-10', '2026-09-10', '2026-09-11', '2026-09-10', '2026-09-10'],
    'aqi': [92, 85, 92, 110, 88, 85] 
}
df = pd.DataFrame(data)

# 1. Count Total Exact Duplicates
# Evaluates all columns. Returns 2 because Salt Lake (Row 2) and New Town (Row 5) 
# are exact copies of Row 0 and Row 1.
total_dupes = df.duplicated().sum()
print(f"Total exact duplicate rows: {total_dupes}")

# 2. Count Duplicates Based on Specific Columns
# Evaluates only 'station' and 'date'. Returns 3 because New Town on 2026-09-10 
# appears three times (leaving 2 duplicates to be counted).
subset_dupes = df.duplicated(subset=['station', 'date']).sum()
print(f"Total duplicate records for the same station/date: {subset_dupes}")

# 3. View the Actual Boolean Mask
# Useful for filtering the DataFrame to look at the duplicates directly
is_duplicate = df.duplicated(subset=['station', 'date'], keep=False)
print("\nRows flagged as duplicates (including originals):")
display(df[is_duplicate].sort_values(by='station'))

# 4. Detailed Frequency Breakdown
# Use value_counts() to see exactly how many times each station/date combination appears.
# The reset_index(name='count') turns the Series back into a clean DataFrame.
duplicate_breakdown = df[['station', 'date']].value_counts().reset_index(name='count')
print("\nFrequency of each record combination:")
display(duplicate_breakdown)

Total exact duplicate rows: 2
Total duplicate records for the same station/date: 3

Rows flagged as duplicates (including originals):

     station        date  aqi
1   New Town  2026-09-10   85
4   New Town  2026-09-10   88
5   New Town  2026-09-10   85
0  Salt Lake  2026-09-10   92
2  Salt Lake  2026-09-10   92

Frequency of each record combination:

     station        date  count
0   New Town  2026-09-10      3
1  Salt Lake  2026-09-10      2
2      Bally  2026-09-11      1

#### **31. How do you handle missing values?**
Handling missing values (`NaN`) in Pandas fundamentally relies on three core operations: detecting the gaps, dropping incomplete records, or imputing (filling) the missing data with calculated replacements.

Because air quality datasets frequently suffer from sensor downtime, knowing how to handle gaps without aggressively deleting valuable surrounding data is critical.

**Core Missing Data Methods**  
* **`isna()` / `isnull()`:** Returns a boolean mask of your DataFrame where `True` represents a missing value.
* **`dropna()`:** Deletes entire rows (or columns) that contain missing values.
* **`fillna()`:** Replaces `NaN` with a specific static value, a statistical metric (like the mean), or a directional fill (copying the previous row's value).
* **`interpolate()`:** Estimates missing values by drawing a mathematical line between the data points before and after the gap—ideal for time-series sensor data.

In [31]:
import pandas as pd
import numpy as np

# Creating a time-series dataset with missing sensor readings
data = {
    'date': pd.date_range(start='2026-09-07', periods=6),
    'station': ['Koramangala'] * 6,
    'aqi': [110, np.nan, 115, 120, np.nan, 130],
    'pm25': [45.0, 48.2, np.nan, np.nan, 55.1, 60.0]
}
df = pd.DataFrame(data)
print("Original Dataset with Missing Values:")
display(df)

# 1. Detecting Missing Values
# Chaining isna() with sum() gives a total count of missing values per column
missing_counts = df.isna().sum()
print("\nMissing Values per Column:\n", missing_counts)

# 2. Dropping Incomplete Rows
# The 'subset' parameter ensures we only drop the row if 'aqi' is missing. 
# If 'pm25' is missing but 'aqi' is intact, the row is kept.
dropped_df = df.dropna(subset=['aqi'])
print("\nDropped rows missing AQI data:")
display(dropped_df)

# 3. Statistical Imputation (Mean/Median)
# Replacing missing PM2.5 values with the mathematical average of the column
mean_pm25 = df['pm25'].mean()
df_mean_fill = df.copy()
df_mean_fill['pm25'] = df_mean_fill['pm25'].fillna(mean_pm25)
print(f"\nFilled PM2.5 with Column Mean ({mean_pm25:.2f}):")
display(df_mean_fill[['date', 'pm25']])

# 4. Forward Filling (ffill)
# Replaces NaN with the last known valid observation. 
# Highly common in sensor data when a sensor temporarily goes offline.
df_ffill = df.copy()
df_ffill['aqi'] = df_ffill['aqi'].ffill()
print("\nForward Filled AQI (Carries previous value down):")
display(df_ffill[['date', 'aqi']])

# 5. Linear Interpolation
# Draws a straight line between the points surrounding the NaN.
# If Day 1 is 48.2 and Day 4 is 55.1, it evenly calculates the missing Days 2 and 3.
df_interp = df.copy()
df_interp['pm25'] = df_interp['pm25'].interpolate()
print("\nInterpolated PM2.5 Data:")
display(df_interp[['date', 'pm25']])

Original Dataset with Missing Values:

        date      station    aqi  pm25
0 2026-09-07  Koramangala  110.0  45.0
1 2026-09-08  Koramangala    NaN  48.2
2 2026-09-09  Koramangala  115.0   NaN
3 2026-09-10  Koramangala  120.0   NaN
4 2026-09-11  Koramangala    NaN  55.1
5 2026-09-12  Koramangala  130.0  60.0

Missing Values per Column:
 date       0
station    0
aqi        2
pm25       2
dtype: int64

Dropped rows missing AQI data:

        date      station    aqi  pm25
0 2026-09-07  Koramangala  110.0  45.0
2 2026-09-09  Koramangala  115.0   NaN
3 2026-09-10  Koramangala  120.0   NaN
5 2026-09-12  Koramangala  130.0  60.0

Filled PM2.5 with Column Mean (52.08):

        date    pm25
0 2026-09-07  45.000
1 2026-09-08  48.200
2 2026-09-09  52.075
3 2026-09-10  52.075
4 2026-09-11  55.100
5 2026-09-12  60.000

Forward Filled AQI (Carries previous value down):

        date    aqi
0 2026-09-07  110.0
1 2026-09-08  110.0
2 2026-09-09  115.0
3 2026-09-10  120.0
4 2026-09-11  120.0
5 2026-09-12  130.0

Interpolated PM2.5 Data:

        date  pm25
0 2026-09-07  45.0
1 2026-09-08  48.2
2 2026-09-09  50.5
3 2026-09-10  52.8
4 2026-09-11  55.1
5 2026-09-12  60.0

#### **32. Difference between dropna() and fillna()?**
The fundamental difference lies in their approach to data integrity: `dropna()` **removes** incomplete records entirely, whereas `fillna()` **retains** the records by imputing (guessing or assigning) substitute values for the missing data.

| Feature | `dropna()` (Deletion) | `fillna()` (Imputation) |
| --- | --- | --- |
| **Action** | Deletes rows (or columns) containing `NaN`. | Replaces `NaN` with a specified value or calculation. |
| **Dataset Size** | Reduces the total number of rows/columns. | Keeps the exact original dimensions of the dataset. |
| **Statistical Risk** | Loss of valuable data in the non-missing columns of the dropped row. | Introduction of bias or artificial trends if the substituted value is inaccurate. |
| **Best Use Case** | When missing data represents a tiny fraction of a massive dataset, or when a row is completely blank. | When data is scarce, time-series continuity is required, or the missing value can be logically deduced (e.g., filling missing sensor data with the column mean). |

In [32]:
import pandas as pd
import numpy as np

# Creating a dataset where one sensor failed temporarily
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'New Town'],
    'aqi': [115, np.nan, 92, 85],
    'pm25': [48.2, np.nan, 40.5, 38.1]
}
df = pd.DataFrame(data)
print(f"Original Shape: {df.shape}")
display(df)

# 1. The dropna() Approach
# The entire row for 'Bally' is completely removed from the dataset.
# The DataFrame shrinks from 4 rows to 3 rows.
dropped_df = df.dropna()
print(f"\nAfter dropna() Shape: {dropped_df.shape}")
display(dropped_df)

# 2. The fillna() Approach
# The row for 'Bally' is preserved. The missing numeric values are 
# replaced with a static placeholder (e.g., 0) or a statistical metric.
# The DataFrame remains at 4 rows.
filled_df = df.fillna(0)
print(f"\nAfter fillna(0) Shape: {filled_df.shape}")
display(filled_df)

Original Shape: (4, 3)

     station    aqi  pm25
0     Howrah  115.0  48.2
1      Bally    NaN   NaN
2  Salt Lake   92.0  40.5
3   New Town   85.0  38.1

After dropna() Shape: (3, 3)

     station    aqi  pm25
0     Howrah  115.0  48.2
2  Salt Lake   92.0  40.5
3   New Town   85.0  38.1

After fillna(0) Shape: (4, 3)

     station    aqi  pm25
0     Howrah  115.0  48.2
1      Bally    0.0   0.0
2  Salt Lake   92.0  40.5
3   New Town   85.0  38.1

#### **33. How do you replace missing values with the mean?**
Replacing missing values with the mean requires calculating the mathematical average of a column using `.mean()` and passing that result directly into `.fillna()`.

It is highly recommended to perform this operation on a specific column or via a dictionary mapping, rather than applying it across the entire DataFrame. Attempting to run `df.fillna(df.mean())` globally will throw a `TypeError` in modern Pandas if your dataset contains string or categorical columns.

In [33]:
import pandas as pd
import numpy as np

# Creating a dataset with missing sensor readings
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'New Town', 'Park Street'],
    'aqi': [115, np.nan, 92, np.nan, 105],
    'pm25': [48.2, 45.0, np.nan, 38.1, 42.1]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Single Column Imputation (Recommended)
# Calculate the mean of the column (Pandas automatically ignores NaNs during calculation)
aqi_mean = df['aqi'].mean()
print(f"\nCalculated AQI Mean: {aqi_mean}")

# Fill the missing values and reassign back to the column
df['aqi'] = df['aqi'].fillna(aqi_mean)

print("\nAfter Filling AQI with Mean:")
display(df)

# 2. Multiple Column Imputation Using a Dictionary
# This is the cleanest way to fill multiple columns with their respective means simultaneously
# Let's reset the dataframe for this example
df_raw = pd.DataFrame(data)

# Create a dictionary where the key is the column name and the value is the calculated mean
fill_values = {
    'aqi': df_raw['aqi'].mean(),
    'pm25': df_raw['pm25'].mean()
}

# Passing the dictionary to fillna() applies the specific mean to the specific column
df_filled_all = df_raw.fillna(value=fill_values)

print("\nAfter Filling Multiple Columns with Their Respective Means:")
display(df_filled_all)

Original Dataset:

       station    aqi  pm25
0       Howrah  115.0  48.2
1        Bally    NaN  45.0
2    Salt Lake   92.0   NaN
3     New Town    NaN  38.1
4  Park Street  105.0  42.1

Calculated AQI Mean: 104.0

After Filling AQI with Mean:

       station    aqi  pm25
0       Howrah  115.0  48.2
1        Bally  104.0  45.0
2    Salt Lake   92.0   NaN
3     New Town  104.0  38.1
4  Park Street  105.0  42.1

After Filling Multiple Columns with Their Respective Means:

       station    aqi   pm25
0       Howrah  115.0  48.20
1        Bally  104.0  45.00
2    Salt Lake   92.0  43.35
3     New Town  104.0  38.10
4  Park Street  105.0  42.10

#### **34. How do you detect missing values?**
Pandas provides two identical methods—`isna()` and `isnull()`—to detect missing data. They return a boolean mask of the exact same dimensions as your DataFrame, where `True` indicates a missing value (`NaN` or `None`) and `False` indicates valid data.

**Common Detection Techniques**  
* **The Mask (`df.isna()`):** Best for visual inspection on small datasets or as a foundational step for conditional filtering.
* **Column Totals (`df.isna().sum()`):** The most common diagnostic step. It sums the `True` values (which equal 1) to give you an exact count of missing records per column.
* **Boolean Check (`df.isna().any()`):** Returns a simple True/False per column, answering "Does this column contain *at least one* missing value?"

In [34]:
import pandas as pd
import numpy as np

# Creating a sample dataset with missing values
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'New Town', 'Park Street'],
    'aqi': [115, np.nan, 92, np.nan, 105],
    'pm25': [48.2, 45.0, np.nan, 38.1, 42.1],
    'is_active': [True, True, True, False, np.nan]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. The Boolean Mask
# df.isnull() behaves exactly the same way.
print("\nBoolean Mask of Missing Values:")
display(df.isna())

# 2. Total Missing Values per Column (Most Common)
# Sums the True values vertically down each column.
missing_counts = df.isna().sum()
print("\nMissing values count per column:")
print(missing_counts)

# 3. Quick Boolean Check
# Useful for writing automated checks in data pipelines.
has_missing = df.isna().any()
print("\nDoes the column contain ANY missing values?")
print(has_missing)

# 4. Total Missing Values in the Entire DataFrame
# Chaining sum() twice adds up all the column totals.
total_missing = df.isna().sum().sum()
print(f"\nTotal missing data points in entire dataset: {total_missing}")

Original Dataset:

       station    aqi  pm25 is_active
0       Howrah  115.0  48.2      True
1        Bally    NaN  45.0      True
2    Salt Lake   92.0   NaN      True
3     New Town    NaN  38.1     False
4  Park Street  105.0  42.1       NaN

Boolean Mask of Missing Values:

   station    aqi   pm25  is_active
0    False  False  False      False
1    False   True  False      False
2    False  False   True      False
3    False   True  False      False
4    False  False  False       True

Missing values count per column:
station      0
aqi          2
pm25         1
is_active    1
dtype: int64

Does the column contain ANY missing values?
station      False
aqi           True
pm25          True
is_active     True
dtype: bool

Total missing data points in entire dataset: 4

#### **35. Difference between isna() and notna()?**
`isna()` and `notna()` are exact logical opposites. They both return a boolean mask of your dataset, but they invert which elements evaluate to `True`.

* **`isna()`:** Returns `True` if the data is **missing** (`NaN` or `None`). It is primarily used to count gaps or to extract the broken rows for inspection.
* **`notna()`:** Returns `True` if the data is **valid**. It is primarily used inside brackets for conditional filtering to temporarily exclude missing values from a calculation without permanently dropping them.

In [35]:
import pandas as pd
import numpy as np

# Creating a sample dataset with missing sensor readings
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'New Town'],
    'aqi': [115, np.nan, 92, np.nan]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Comparing the Masks
# Notice how the True/False values are perfectly inverted
print("\nisna() Mask (True = Missing):")
display(df.isna())

print("\nnotna() Mask (True = Valid):")
display(df.notna())

# 2. Using isna() to Inspect Bad Data
# Extracts only the rows where the sensor failed
failed_sensors = df[df['aqi'].isna()]
print("\nIsolating rows WITH missing data using isna():")
display(failed_sensors)

# 3. Using notna() to Filter for Good Data
# Extracts only the rows with valid readings for analysis
# (This is functionally equivalent to df.dropna(subset=['aqi']))
valid_data = df[df['aqi'].notna()]
print("\nIsolating rows with VALID data using notna():")
display(valid_data)

Original Dataset:

     station    aqi
0     Howrah  115.0
1      Bally    NaN
2  Salt Lake   92.0
3   New Town    NaN

isna() Mask (True = Missing):

   station    aqi
0    False  False
1    False   True
2    False  False
3    False   True

notna() Mask (True = Valid):

   station    aqi
0     True   True
1     True  False
2     True   True
3     True  False

Isolating rows WITH missing data using isna():

    station  aqi
1     Bally  NaN
3  New Town  NaN

Isolating rows with VALID data using notna():

     station    aqi
0     Howrah  115.0
2  Salt Lake   92.0

#### **36. How do you add a new column?**
You can add a new column to a Pandas DataFrame using standard bracket assignment, mathematical derivation from existing columns, or specialized methods like `insert()` and `assign()`. By default, newly assigned columns are appended to the far right of the DataFrame.

**Common Column Creation Methods**  
* **Bracket Assignment (`df['Col'] = ...`)**: The standard approach. It modifies the DataFrame in place and is used to add static values, lists, or calculated mathematical series.
* **The `insert()` Method**: Allows you to specify exactly where (at which integer index position) the new column should appear, rather than appending it to the end.
* **The `assign()` Method**: Returns a *new* DataFrame with the added column, making it ideal for method chaining because it leaves the original dataset untouched.

In [36]:
import pandas as pd

# Creating a standard dataset
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'New Town'],
    'aqi': [115, 110, 92, 85],
    'pm25': [48.2, 45.0, 40.5, 38.1]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Direct Assignment (Scalar Value)
# Broadcasts a single static value across every row in the new column
df['city'] = 'Kolkata'
print("\nAdded a static 'city' column:")
display(df)

# 2. Direct Assignment (List of Values)
# The list MUST be the exact same length as the DataFrame
df['zone'] = ['West', 'North', 'East', 'East']
print("\nAdded a 'zone' column from a list:")
display(df)

# 3. Derived / Calculated Column
# Creating a new column by applying mathematical operations to existing columns
df['pm25_ratio'] = df['pm25'] / df['aqi']
print("\nAdded a calculated 'pm25_ratio' column:")
display(df)

# 4. The insert() Method
# Syntax: df.insert(loc, column_name, value)
# 'loc=1' places the new column immediately after 'station' (which is at index 0)
df.insert(1, 'sensor_id', [101, 102, 103, 104])
print("\nInserted 'sensor_id' at specific position (index 1):")
display(df)

# 5. The assign() Method (Method Chaining)
# This does NOT modify the original 'df'. It returns a brand new DataFrame.
df_chained = df.assign(
    is_hazardous = df['aqi'] > 100,
    aqi_doubled = df['aqi'] * 2
)
print("\nUsing assign() to create multiple columns simultaneously:")
display(df_chained)

Original Dataset:

     station  aqi  pm25
0     Howrah  115  48.2
1      Bally  110  45.0
2  Salt Lake   92  40.5
3   New Town   85  38.1

Added a static 'city' column:

     station  aqi  pm25     city
0     Howrah  115  48.2  Kolkata
1      Bally  110  45.0  Kolkata
2  Salt Lake   92  40.5  Kolkata
3   New Town   85  38.1  Kolkata

Added a 'zone' column from a list:

     station  aqi  pm25     city   zone
0     Howrah  115  48.2  Kolkata   West
1      Bally  110  45.0  Kolkata  North
2  Salt Lake   92  40.5  Kolkata   East
3   New Town   85  38.1  Kolkata   East

Added a calculated 'pm25_ratio' column:

     station  aqi  pm25     city   zone  pm25_ratio
0     Howrah  115  48.2  Kolkata   West    0.419130
1      Bally  110  45.0  Kolkata  North    0.409091
2  Salt Lake   92  40.5  Kolkata   East    0.440217
3   New Town   85  38.1  Kolkata   East    0.448235

Inserted 'sensor_id' at specific position (index 1):

     station  sensor_id  aqi  pm25     city   zone  pm25_ratio
0     Howrah        101  115  48.2  Kolkata   West    0.419130
1      Bally        102  110  45.0  Kolkata  North    0.409091
2  Salt Lake        103   92  40.5  Kolkata   East    0.440217
3   New Town        104   85  38.1  Kolkata   East    0.448235

Using assign() to create multiple columns simultaneously:

,station,sensor_id,aqi,pm25,city,zone,pm25_ratio,is_hazardous,aqi_doubled
0,Howrah,101,115,48.2,Kolkata,West,0.419130,True,230
1,Bally,102,110,45.0,Kolkata,North,0.409091,True,220
2,Salt Lake,103,92,40.5,Kolkata,East,0.440217,False,184
3,New Town,104,85,38.1,Kolkata,East,0.448235,False,170

#### **37. How do you delete a column?**
The `drop()` method is the primary tool for removing columns from a dataset. By default, it returns a new DataFrame with the specified columns removed, leaving your original dataset entirely intact unless you explicitly pass the parameter `inplace=True`.

**Column Deletion Methods**  
* **`drop(columns=[...])`:** The safest and most readable Pandas method. It clearly indicates you are targeting columns rather than rows.
* **`drop([names], axis=1)`:** The traditional syntax. It requires explicitly setting `axis=1` (columns) because `axis=0` (rows) is the default.
* **`del df['Column']`:** A built-in Python command that deletes the column *in place* immediately. It is fast, but it cannot drop multiple columns at once and cannot be used in method chaining.
* **`pop('Column')`:** Removes the column in place but also returns it as a Series. This is highly useful when you need to extract a target variable for machine learning and remove it from the training dataset in one step.

In [37]:
import pandas as pd

# Creating a dataset with extra, unnecessary columns
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'New Town'],
    'aqi': [115, 110, 92, 85],
    'pm25': [48.2, 45.0, 40.5, 38.1],
    'temp_c': [32, 33, 31, 31],
    'technician': ['Amit', 'Amit', 'Raj', 'Raj']
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Using the 'columns' parameter (Recommended)
# Safely drops a single column and returns a new DataFrame
df_dropped_single = df.drop(columns=['technician'])
print("\nDropped 'technician' column:")
display(df_dropped_single)

# 2. Dropping multiple columns using axis=1
# Passing a list of names and specifying the column axis
df_dropped_multi = df.drop(['temp_c', 'technician'], axis=1)
print("\nDropped multiple columns ('temp_c' and 'technician'):")
display(df_dropped_multi)

# 3. In-place deletion using 'del'
# This modifies 'df' instantly without needing assignment.
del df['technician']
print("\nAfter 'del df[\"technician\"]' (Modifies original):")
display(df)

# 4. Extracting and deleting simultaneously with pop()
# Removes 'pm25' from the DataFrame and saves it to the 'target_variable' Series
target_variable = df.pop('pm25')
print("\nExtracted 'pm25' Series using pop():")
print(target_variable)
print("\nDataFrame after pop() (Notice 'pm25' is gone):")
display(df)

Original Dataset:

     station  aqi  pm25  temp_c technician
0     Howrah  115  48.2      32       Amit
1      Bally  110  45.0      33       Amit
2  Salt Lake   92  40.5      31        Raj
3   New Town   85  38.1      31        Raj

Dropped 'technician' column:

     station  aqi  pm25  temp_c
0     Howrah  115  48.2      32
1      Bally  110  45.0      33
2  Salt Lake   92  40.5      31
3   New Town   85  38.1      31

Dropped multiple columns ('temp_c' and 'technician'):

     station  aqi  pm25
0     Howrah  115  48.2
1      Bally  110  45.0
2  Salt Lake   92  40.5
3   New Town   85  38.1

After 'del df["technician"]' (Modifies original):

     station  aqi  pm25  temp_c
0     Howrah  115  48.2      32
1      Bally  110  45.0      33
2  Salt Lake   92  40.5      31
3   New Town   85  38.1      31

Extracted 'pm25' Series using pop():
0    48.2
1    45.0
2    40.5
3    38.1
Name: pm25, dtype: float64

DataFrame after pop() (Notice 'pm25' is gone):

     station  aqi  temp_c
0     Howrah  115      32
1      Bally  110      33
2  Salt Lake   92      31
3   New Town   85      31

#### **38. Difference between drop() and del?**
The fundamental difference is that `drop()` is a Pandas method that safely returns a new modified DataFrame by default, whereas `del` is a built-in Python keyword that forces an immediate, irreversible, in-place deletion.

**Key Behavioral Differences**  
| Feature | `drop()` | `del` |
| --- | --- | --- |
| **Origin** | Pandas DataFrame method. | Built-in Python dictionary keyword. |
| **Default Behavior** | Non-destructive. Returns a new DataFrame unless `inplace=True` is passed. | Destructive. Instantly mutates the original DataFrame in memory. |
| **Scope** | Can delete rows (`axis=0`) or columns (`axis=1`). | Can ONLY delete columns. |
| **Capacity** | Can remove multiple columns simultaneously using a list. | Can only remove one column per statement. |
| **Method Chaining** | Fully supported (e.g., `df.drop(...).fillna(...)`). | Not supported. |

In [38]:
import pandas as pd

# Creating a dataset with extra columns
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'New Town'],
    'aqi': [115, 110, 92, 85],
    'temp_c': [32, 33, 31, 31],
    'humidity': [75, 78, 70, 72]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. The drop() Method (Safe / Non-destructive)
# Creates a completely new DataFrame in memory. The original 'df' is untouched.
df_clean = df.drop(columns=['temp_c'])

print("\nResult of df.drop():")
display(df_clean)
print("\nOriginal df AFTER drop() (Still has temp_c):")
display(df)

# 2. The del Keyword (Destructive)
# Instantly wipes the column from the original 'df' in memory.
del df['humidity']

print("\nOriginal df AFTER del (humidity is permanently gone):")
display(df)

# 3. Attempting multiple deletions
df.drop(columns=['temp_c'])     # Works perfectly
try:
    del df['humidity']              # Throws a KeyError/SyntaxError
except Exception as e:
    print(e)

Original Dataset:

     station  aqi  temp_c  humidity
0     Howrah  115      32        75
1      Bally  110      33        78
2  Salt Lake   92      31        70
3   New Town   85      31        72

Result of df.drop():

     station  aqi  humidity
0     Howrah  115        75
1      Bally  110        78
2  Salt Lake   92        70
3   New Town   85        72

Original df AFTER drop() (Still has temp_c):

     station  aqi  temp_c  humidity
0     Howrah  115      32        75
1      Bally  110      33        78
2  Salt Lake   92      31        70
3   New Town   85      31        72

Original df AFTER del (humidity is permanently gone):

     station  aqi  temp_c
0     Howrah  115      32
1      Bally  110      33
2  Salt Lake   92      31
3   New Town   85      31

'humidity'

#### **39. How do you change data types?**
The `.astype()` method is the standard way to change (cast) data types in Pandas. For more complex conversions involving date formats or messy string data containing text, Pandas provides specialized `to_datetime()` and `to_numeric()` functions.

**Key Type Conversion Methods**  
* **`astype()`:** The standard tool for clean data. Used to convert floats to integers, integers to strings, or strings to memory-efficient categoricals. It will fail if it encounters data it doesn't know how to translate (like converting the string "missing" to an integer).
* **`pd.to_numeric()`:** Converts strings to numeric types (float/int). Crucially, it includes an `errors='coerce'` parameter that forces unparseable text into `NaN` instead of throwing an error.
* **`pd.to_datetime()`:** Intelligently parses date strings (like "2026-09-12" or "12/09/2026") into robust Pandas Timestamp objects, unlocking time-series capabilities.

In [39]:
import pandas as pd

# Creating a dataset simulating a messy CSV import
data = {
    'date': ['2026-09-10', '2026-09-11', '2026-09-12'], # Imported as strings (object)
    'station': ['Howrah', 'Bally', 'Salt Lake'],
    'aqi': [115.0, 110.0, 92.0],                        # Imported as floats
    'pm25': ['48.2', '45.0', 'Sensor Down']             # Imported as strings due to text
}
df = pd.DataFrame(data)

print("Original Data Types:\n", df.dtypes)

# 1. Standard Conversion with astype()
# Converting AQI from float to integer (drops the decimal)
# Note: astype() does NOT happen in-place. You must reassign it.
df['aqi'] = df['aqi'].astype(int)

# 2. Handling Messy Strings with to_numeric()
# Trying df['pm25'].astype(float) would crash because of "Sensor Down".
# errors='coerce' forces the text "Sensor Down" to become NaN.
df['pm25'] = pd.to_numeric(df['pm25'], errors='coerce')

# 3. Converting to Datetime
# Converts the string dates into specialized Timestamp objects
df['date'] = pd.to_datetime(df['date'])

# 4. Memory Optimization (Categoricals)
# 'station' has a finite set of repeating values. Converting it to 'category' 
# saves significant memory on massive datasets.
df['station'] = df['station'].astype('category')

print("\nCleaned Dataset")
display(df)
print("\nNew Data Types:\n", df.dtypes)

Original Data Types:
 date        object
station     object
aqi        float64
pm25        object
dtype: object

Cleaned Dataset

        date    station  aqi  pm25
0 2026-09-10     Howrah  115  48.2
1 2026-09-11      Bally  110  45.0
2 2026-09-12  Salt Lake   92   NaN

New Data Types:
 date       datetime64[ns]
station          category
aqi                 int64
pm25              float64
dtype: object

#### **40. What is astype()?**
The `.astype()` method is the fundamental Pandas function for explicitly casting a Series or an entire DataFrame from one data type to another. It is a strict operation, meaning it will immediately throw a `ValueError` if it encounters even a single data point that cannot be cleanly converted into the target type.

**Key Capabilities**  
* **Dictionary Mapping:** You can pass a dictionary to `.astype()` to cast multiple columns to entirely different data types simultaneously in a single line of code.
* **Memory Optimization:** It is heavily used to downcast data (e.g., converting a 64-bit integer to a 32-bit integer) or to convert repetitive text strings (`object`) into memory-efficient `category` types.
* **Boolean to Integer Casting:** It natively translates boolean masks (`True` / `False`) into binary integers (`1` / `0`), a mandatory step before feeding categorical data into many machine learning algorithms.
* **Not In-Place:** It always returns a new Pandas object. You must reassign the result to overwrite your existing data.

In [40]:
import pandas as pd

# Creating a dataset with inefficient or incorrect data types
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'Howrah', 'Bally'], # object
    'aqi': [115.0, 110.0, 92.0, 120.0, 105.0],                      # float64
    'is_active': [True, True, False, True, False]                   # bool
}
df = pd.DataFrame(data)

print("Original Data Types:\n", df.dtypes)

# 1. Single Column Casting
# Converting AQI from a float to an integer (drops decimals)
df['aqi'] = df['aqi'].astype(int)
print("\nAfter casting 'aqi' to int:\n", df['aqi'].head(2))

# 2. Boolean to Integer Casting
# Translates True to 1 and False to 0
df['is_active'] = df['is_active'].astype(int)
print("\nAfter casting 'is_active' to int:\n", df['is_active'].head(2))

# 3. Multi-Column Casting with a Dictionary
# Resetting the dataframe for the demonstration
df_raw = pd.DataFrame(data)

# Pass a dictionary specifying exactly which column gets which type
type_mapping = {
    'station': 'category', # Great for repeating text strings
    'aqi': 'int32',        # Downcasting to save memory
    'is_active': 'int8'    # Booleans only need the smallest integer type
}

df_optimized = df_raw.astype(type_mapping)

print("\nOptimized Data Types using Dictionary:\n", df_optimized.dtypes)

# 4. The Strictness of astype()
# If we added a string to a numeric column:
try:
    df['aqi'] = [115.0, 110.0, 'Sensor Error', 120.0, 105.0]
    df['aqi'].astype(int)  # This would trigger a ValueError immediately.
except Exception as e:
    print("\n", e)

Original Data Types:
 station       object
aqi          float64
is_active       bool
dtype: object

After casting 'aqi' to int:
 0    115
1    110
Name: aqi, dtype: int64

After casting 'is_active' to int:
 0    1
1    1
Name: is_active, dtype: int64

Optimized Data Types using Dictionary:
 station      category
aqi             int32
is_active        int8
dtype: object

 invalid literal for int() with base 10: 'Sensor Error'

#### **41. How do you apply a function to a column?**
The `.apply()` method is the most versatile tool for executing custom operations on a column. It takes a function—whether it is a built-in Python function, a custom `def` block, or a one-line `lambda` expression—and runs it individually on every single element within that Series.

**Key Application Methods**  
* **Custom Functions (`def`):** Best for complex logic that involves multiple `if/else` conditions (like categorizing AQI numbers into risk levels).
* **Lambda Functions (`lambda`):** Best for quick, simple transformations that only require a single line of code, preventing you from cluttering your script with tiny functions.
* **Built-in Functions:** You can pass standard Python functions like `len`, `str`, or `type` directly into `.apply()` without calling them (e.g., `apply(len)`, not `apply(len())`).

*Note on performance: While extremely flexible, `.apply()` is effectively a standard Python `for` loop under the hood. For simple math, standard Pandas vectorized operations (like `df['aqi'] * 2`) are significantly faster.*

In [41]:
import pandas as pd

# Creating a dataset with raw air quality data
data = {
    'station': ['howrah', 'bally', 'salt lake', 'new town', 'park street'],
    'aqi': [115, 85, 210, 45, 160],
    'pm25': [48.2, 38.1, 110.5, 22.0, 65.0]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Applying a Custom Function (Categorization)
def categorize_aqi(value):
    """Converts a numeric AQI value into a health risk category."""
    if pd.isna(value):
        return 'Unknown'
    elif value <= 50:
        return 'Good'
    elif value <= 100:
        return 'Satisfactory'
    elif value <= 200:
        return 'Moderate'
    else:
        return 'Poor'

# Pass the name of the function WITHOUT parentheses
df['health_risk'] = df['aqi'].apply(categorize_aqi)
print("\nAfter Applying Custom Function (categorize_aqi):")
display(df[['station', 'aqi', 'health_risk']])

# 2. Applying a Lambda Function (Quick Formatting)
# Capitalizes the first letter of each word in the station name
df['station_clean'] = df['station'].apply(lambda x: x.title())

# 3. Applying a Built-in Function
# Calculates the number of characters in each station name
df['name_length'] = df['station'].apply(len)

print("\nAfter Applying Lambda and Built-in Functions:")
display(df[['station_clean', 'name_length']])

Original Dataset:

       station  aqi   pm25
0       howrah  115   48.2
1        bally   85   38.1
2    salt lake  210  110.5
3     new town   45   22.0
4  park street  160   65.0

After Applying Custom Function (categorize_aqi):

       station  aqi   health_risk
0       howrah  115      Moderate
1        bally   85  Satisfactory
2    salt lake  210          Poor
3     new town   45          Good
4  park street  160      Moderate

After Applying Lambda and Built-in Functions:

  station_clean  name_length
0        Howrah            6
1         Bally            5
2     Salt Lake            9
3      New Town            8
4   Park Street           11

#### **42. What is apply()?**
The `.apply()` method is an iterator that executes a specified function across an entire Pandas Series or along a specific axis of a DataFrame. It acts as a flexible bridge between custom Python logic and Pandas data structures when built-in methods fall short.

**Mechanics and Behavior**  
* **Execution Strategy:** Under the hood, `.apply()` functions similarly to a standard Python `for` loop. It maps your function to each individual element (if used on a Series) or each row/column (if used on a DataFrame).
* **Axis Control:** When applied to a full DataFrame, the `axis` parameter dictates the direction. `axis=0` (the default) passes entire columns to your function one by one. `axis=1` passes entire rows, allowing you to build complex calculations that use multiple columns simultaneously.
* **The Performance Penalty:** Because it relies on standard Python execution rather than the heavily optimized, C-based architecture of native Pandas methods, `.apply()` is significantly slower. It should be reserved strictly for complex logic (like custom string parsing or multi-variable conditional logic) where standard vectorized math operations cannot be used.

In [42]:
import pandas as pd

# Creating a dataset with multiple pollutant readings
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake'],
    'pm25': [48.2, 65.0, 40.5],
    'pm10': [110.0, 145.2, 85.2]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Applying a function across an entire row (axis=1)
# The function receives the entire row as a Series, allowing us to reference multiple columns.
def calculate_primary_pollutant(row):
    """Determines which pollutant is dominating the air quality profile."""
    if row['pm25'] > (row['pm10'] * 0.5):
        return 'Fine Particulate Heavy (PM2.5)'
    else:
        return 'Coarse Dust Heavy (PM10)'

# By setting axis=1, we process row-by-row instead of column-by-column
df['pollution_profile'] = df.apply(calculate_primary_pollutant, axis=1)

print("\nAfter DataFrame apply() with axis=1:")
display(df)

# 2. Vectorization vs. apply()
df['total_particulates'] = df.apply(lambda row: row['pm25'] + row['pm10'], axis=1) # BAD
df['total_particulates'] = df['pm25'] + df['pm10']  # GOOD # Much faster!

Original Dataset:

     station  pm25   pm10
0     Howrah  48.2  110.0
1      Bally  65.0  145.2
2  Salt Lake  40.5   85.2

After DataFrame apply() with axis=1:

     station  pm25   pm10         pollution_profile
0     Howrah  48.2  110.0  Coarse Dust Heavy (PM10)
1      Bally  65.0  145.2  Coarse Dust Heavy (PM10)
2  Salt Lake  40.5   85.2  Coarse Dust Heavy (PM10)

#### **43. Difference between apply(), map(), and applymap()?**
These three methods all execute functions across your data, but their fundamental differences lie in **which Pandas object they target** (Series vs. DataFrame) and **how they iterate** (element-by-element vs. axis-by-axis).

*Important Note: As of Pandas 2.1.0, `applymap()` has been formally deprecated and renamed to `DataFrame.map()`. Modern codebases should exclusively use `map()`.*

**Method Comparison**  
| Method | Target Object | Iteration Style | Primary Use Case |
| --- | --- | --- | --- |
| **`map()`** | Series | Element-wise | Dictionary lookups, value substitution, or applying a function to a single column. |
| **`apply()`** | Series or DataFrame | Element-wise (Series) or Axis-wise (DataFrame) | Executing complex logic across multiple columns simultaneously (`axis=1`). |
| **`applymap()`** *(Deprecated)* | DataFrame | Element-wise | Applying a formatting function to every single cell in a grid (replaced by `df.map()`). |

In [43]:
import pandas as pd
import numpy as np

# Creating a dataset of particulate matter readings
data = {
    'station_code': ['HWH', 'SLK', 'NTN'],
    'pm25': [48.2, 38.1, 110.5],
    'pm10': [85.0, 60.2, 145.0]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Using map() on a Series
# Ideal for substituting values using a dictionary lookup.
# Notice how unmatched values (if any existed) would become NaN.
zone_dict = {'HWH': 'West', 'SLK': 'East', 'NTN': 'East'}
df['zone'] = df['station_code'].map(zone_dict)
print("\nAfter Series.map() (Dictionary Lookup):")
display(df[['station_code', 'zone']])

# 2. Using apply() on a DataFrame
# Ideal for calculations that require looking at multiple columns in the same row.
# We set axis=1 to pass entire rows to the lambda function.
df['pm_difference'] = df.apply(lambda row: row['pm10'] - row['pm25'], axis=1)
print("\nAfter DataFrame.apply() (Row-by-Row Calculation):")
display(df[['pm25', 'pm10', 'pm_difference']])

# 3. Using DataFrame.map() (Formerly applymap)
# Ideal for formatting or transforming an entire grid of cells simultaneously.
# We apply this only to the numeric columns to avoid formatting strings.
numeric_cols = ['pm25', 'pm10', 'pm_difference']

# In Pandas < 2.1.0, this was: df[numeric_cols].applymap(...)
df_formatted = df.copy()
df_formatted[numeric_cols] = df[numeric_cols].map(lambda x: f"{x:.1f} µg/m³")

print("\nAfter DataFrame.map() (Element-wise Grid Formatting):")
display(df_formatted)

Original Dataset:

  station_code   pm25   pm10
0          HWH   48.2   85.0
1          SLK   38.1   60.2
2          NTN  110.5  145.0

After Series.map() (Dictionary Lookup):

  station_code  zone
0          HWH  West
1          SLK  East
2          NTN  East

After DataFrame.apply() (Row-by-Row Calculation):

    pm25   pm10  pm_difference
0   48.2   85.0           36.8
1   38.1   60.2           22.1
2  110.5  145.0           34.5

After DataFrame.map() (Element-wise Grid Formatting):

  station_code         pm25         pm10  zone pm_difference
0          HWH   48.2 µg/m³   85.0 µg/m³  West    36.8 µg/m³
1          SLK   38.1 µg/m³   60.2 µg/m³  East    22.1 µg/m³
2          NTN  110.5 µg/m³  145.0 µg/m³  East    34.5 µg/m³

#### **44. What is value_counts()?**
The `value_counts()` method is a diagnostic tool that calculates the exact frequency of every unique value within a Pandas Series or DataFrame. By default, it returns a new Series sorted in descending order, making the most common occurrences instantly visible.

**Key Parameters for Data Auditing**  
* **`normalize=True`:** Instead of returning raw counts (e.g., 50), it returns the relative frequency or percentage (e.g., 0.50), which is perfect for understanding class distribution.
* **`dropna=False`:** By default, `value_counts()` completely ignores missing data (`NaN`). Setting this to `False` forces Pandas to include `NaN` as a distinct category in the frequency count.
* **`bins=X`:** When applied to a continuous numerical column, this parameter groups the exact numbers into `X` equal-sized intervals (bins) and counts how many data points fall into each range, effectively acting like a quick histogram.

In [44]:
import pandas as pd
import numpy as np

# Creating a dataset representing multiple daily readings across stations
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'New Town', 'Howrah', 'Bally', 'Salt Lake', 'Bally'],
    'status': ['Poor', 'Moderate', 'Good', 'Moderate', 'Very Poor', np.nan, 'Good', 'Moderate'],
    'pm25': [65.2, 45.1, 22.0, 38.5, 110.1, np.nan, 18.5, 42.0]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Standard Frequency Count
# Counts the occurrences of each air quality status, sorted highest to lowest
status_counts = df['status'].value_counts()
print("\nStandard Value Counts (ignores NaN):")
print(status_counts)

# 2. Including Missing Data
# Forces NaN to appear in the tally so you know exactly how many readings failed
status_with_nan = df['status'].value_counts(dropna=False)
print("\nValue Counts Including NaN:")
print(status_with_nan)

# 3. Normalized Counts (Percentages)
# Returns the proportion of each category (e.g., 0.42 = 42%)
status_percentages = df['status'].value_counts(normalize=True)
print("\nNormalized Counts (Proportions):")
print(status_percentages)

# 4. Binning Continuous Numerical Data
# Instead of counting exact PM2.5 matches (which rarely happen), it groups 
# the PM2.5 values into 3 equal-width intervals and counts the occurrences.
pm25_bins = df['pm25'].value_counts(bins=3)
print("\nContinuous Data Grouped into 3 Bins:")
print(pm25_bins)

# 5. DataFrame value_counts()
# Evaluates exact row combinations. E.g., how many times did Bally report 'Moderate'?
multi_col_counts = df[['station', 'status']].value_counts().reset_index(name='count')
print("\nFrequency of Station + Status Combinations:")
display(multi_col_counts)

Original Dataset:

     station     status   pm25
0     Howrah       Poor   65.2
1      Bally   Moderate   45.1
2  Salt Lake       Good   22.0
3   New Town   Moderate   38.5
4     Howrah  Very Poor  110.1
5      Bally        NaN    NaN
6  Salt Lake       Good   18.5
7      Bally   Moderate   42.0

Standard Value Counts (ignores NaN):
status
Moderate     3
Good         2
Poor         1
Very Poor    1
Name: count, dtype: int64

Value Counts Including NaN:
status
Moderate     3
Good         2
Poor         1
Very Poor    1
NaN          1
Name: count, dtype: int64

Normalized Counts (Proportions):
status
Moderate     0.428571
Good         0.285714
Poor         0.142857
Very Poor    0.142857
Name: proportion, dtype: float64

Continuous Data Grouped into 3 Bins:
(18.407, 49.033]    5
(49.033, 79.567]    1
(79.567, 110.1]     1
Name: count, dtype: int64

Frequency of Station + Status Combinations:

     station     status  count
0      Bally   Moderate      2
1  Salt Lake       Good      2
2     Howrah       Poor      1
3     Howrah  Very Poor      1
4   New Town   Moderate      1

#### **45. What is unique()?**
The `unique()` method extracts an array of all distinct values present in a Pandas Series. While `value_counts()` gives you the frequency of each item, `unique()` simply answers the question: "What are all the different categories or items that exist in this column?"

**Key Characteristics**  
* **Order of Appearance:** It does not sort the results alphabetically or numerically. It returns the unique values in the exact order it first encountered them in the dataset.
* **Returns a NumPy Array:** Unlike most Pandas methods, it returns a standard NumPy array rather than a Pandas Series.
* **Includes Missing Data:** If your column contains missing values, `NaN` (or `None`) will be included in the output array as one of the unique values.
* **The Companion Method (`nunique()`):** If you just want to know *how many* unique values exist (an integer count) rather than seeing the actual values, use `nunique()`.

In [45]:
import pandas as pd
import numpy as np

# Creating a dataset with repeated categorical values and missing data
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'Howrah', 'New Town', 'Bally'],
    'status': ['Poor', 'Moderate', 'Good', 'Poor', np.nan, 'Moderate']
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Extracting Unique Values
# Returns a NumPy array of the distinct stations in order of appearance
unique_stations = df['station'].unique()
print("\nUnique Stations Array:")
print(unique_stations)

# Notice how NaN is included as a distinct value in the status array
unique_status = df['status'].unique()
print("\nUnique Statuses Array (Notice the nan):")
print(unique_status)

# 2. Counting Unique Values with nunique()
# Returns a simple integer. 
# By default, nunique() IGNORES missing values (dropna=True).
count_stations = df['station'].nunique()
print(f"\nTotal number of unique stations: {count_stations}")

count_status = df['status'].nunique()
print(f"Total number of unique statuses (excluding NaN): {count_status}")

# 3. Forcing nunique() to count NaN
count_status_with_nan = df['status'].nunique(dropna=False)
print(f"Total number of unique statuses (including NaN): {count_status_with_nan}")

Original Dataset:

     station    status
0     Howrah      Poor
1      Bally  Moderate
2  Salt Lake      Good
3     Howrah      Poor
4   New Town       NaN
5      Bally  Moderate

Unique Stations Array:
['Howrah' 'Bally' 'Salt Lake' 'New Town']

Unique Statuses Array (Notice the nan):
['Poor' 'Moderate' 'Good' nan]

Total number of unique stations: 4
Total number of unique statuses (excluding NaN): 3
Total number of unique statuses (including NaN): 4

#### **46. What is nunique()?**
The `nunique()` method calculates the exact count of distinct elements within a Pandas Series or DataFrame. While `unique()` returns an array of the actual items, `nunique()` simply returns an integer representing *how many* different items exist.

**Key Characteristics**  
* **Missing Data Handling:** By default, `nunique()` ignores missing values (`NaN`). If a column has three distinct string values and one `NaN`, `nunique()` returns `3`. You must explicitly set `dropna=False` if you want `NaN` counted as a distinct category.
* **Series vs. DataFrame:** When applied to a single column (Series), it returns a single integer. When applied to an entire DataFrame, it returns a new Series displaying the unique count for *every* column simultaneously.
* **Memory Efficiency:** It is highly optimized and much faster than converting `unique()` to a Python list and calculating the length (e.g., `len(df['col'].unique())`).

In [46]:
import pandas as pd
import numpy as np

# Creating a dataset representing multiple daily readings across a few stations
data = {
    'station': ['Howrah', 'Bally', 'Salt Lake', 'Howrah', 'New Town', 'Bally'],
    'status': ['Poor', 'Moderate', 'Good', 'Poor', np.nan, 'Moderate'],
    'sensor_id': [101, 102, 103, 101, 104, 102]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Series nunique() (Default behavior)
# Returns 4 because 'Howrah', 'Bally', 'Salt Lake', and 'New Town' are the distinct items.
station_count = df['station'].nunique()
print(f"\nTotal unique stations: {station_count}")

# 2. Handling Missing Data (NaN)
# Default: Ignores the NaN in the 'status' column (Poor, Moderate, Good) = 3
status_count_default = df['status'].nunique()

# dropna=False: Counts NaN as its own distinct category = 4
status_count_with_nan = df['status'].nunique(dropna=False)

print(f"Unique statuses (excluding NaN): {status_count_default}")
print(f"Unique statuses (including NaN): {status_count_with_nan}")

# 3. DataFrame nunique()
# Evaluates every column in the dataset at once.
# Highly useful for a quick overview of a massive dataset's variety.
all_counts = df.nunique()
print("\nUnique counts across all columns:")
print(all_counts)

Original Dataset:

     station    status  sensor_id
0     Howrah      Poor        101
1      Bally  Moderate        102
2  Salt Lake      Good        103
3     Howrah      Poor        101
4   New Town       NaN        104
5      Bally  Moderate        102

Total unique stations: 4
Unique statuses (excluding NaN): 3
Unique statuses (including NaN): 4

Unique counts across all columns:
station      4
status       3
sensor_id    4
dtype: int64

#### **47. How do you rename index values?**
The `.rename()` method is the safest and most common way to alter specific index labels by passing a dictionary mapping the old names to the new names.

If you need to change every single label at once, you can directly overwrite the `.index` attribute with a new list, though this requires the new list to be the exact same length as the DataFrame.

**Index Renaming Techniques**  
* **Dictionary Mapping (`rename(index={old: new})`):** Targets specific labels. If a label in your dictionary doesn't exist in the index, Pandas simply ignores it without throwing an error.
* **Function Mapping (`rename(index=function)`):** Applies a function (like `str.lower` or a lambda) to every label in the index automatically.
* **Complete Overwrite (`df.index = [...]`):** Replaces the entire index in place. Fast, but rigid.

In [47]:
import pandas as pd

# Creating a dataset with shorthand station codes as the index
data = {
    'aqi': [115, 85, 92],
    'pm25': [48.2, 38.1, 40.5]
}
df = pd.DataFrame(data, index=['HWH', 'NTN', 'SLK'])
print("Original Dataset:")
display(df)

# 1. Renaming specific labels using a dictionary
# Notice we don't have to rename 'SLK' if we don't want to.
# Like most Pandas methods, it returns a new DataFrame unless inplace=True.
renamed_dict = df.rename(index={'HWH': 'Howrah', 'NTN': 'New Town'})
print("\nAfter Dictionary Renaming:")
display(renamed_dict)

# 2. Renaming using a string function
# Converts all uppercase index labels to lowercase
renamed_func = df.rename(index=str.lower)
print("\nAfter Function Renaming (str.lower):")
display(renamed_func)

# 3. Completely overwriting the index
# Modifies the original DataFrame instantly. The list must match the row count.
df.index = ['Station_1', 'Station_2', 'Station_3']
print("\nAfter Complete Index Overwrite:")
display(df)

Original Dataset:

     aqi  pm25
HWH  115  48.2
NTN   85  38.1
SLK   92  40.5

After Dictionary Renaming:

          aqi  pm25
Howrah    115  48.2
New Town   85  38.1
SLK        92  40.5

After Function Renaming (str.lower):

     aqi  pm25
hwh  115  48.2
ntn   85  38.1
slk   92  40.5

After Complete Index Overwrite:

           aqi  pm25
Station_1  115  48.2
Station_2   85  38.1
Station_3   92  40.5

#### **48. How do you reset the index?**
The `reset_index()` method takes your current row labels and moves them back into the DataFrame as a standard column, replacing the index with a default sequential integer index (0, 1, 2...).

**Key Parameters and Use Cases**  
* **`drop`:** By default (`False`), Pandas keeps your old index and inserts it as a new column at the far left of the DataFrame. Setting `drop=True` permanently deletes the old index instead.
* **Restoring Order:** When you filter rows or use `sort_values()`, the original integer index gets scrambled (e.g., 3, 1, 4). `reset_index(drop=True)` is the standard way to cleanly renumber the rows from zero.
* **Flattening GroupBys:** Grouping data often creates complex multi-level indices. Resetting the index flattens the dataset back into a standard, easy-to-read table.

In [48]:
import pandas as pd

# Creating a dataset where the station names are set as the index
data = {
    'aqi': [115, 85, 92, 110],
    'pm25': [48.2, 38.1, 40.5, 45.0]
}
df = pd.DataFrame(data, index=['Howrah', 'New Town', 'Salt Lake', 'Bally'])
df.index.name = 'station' # Giving the index a formal name
print("Original Dataset (Station is the Index):")
display(df)

# 1. Standard Reset
# The 'station' index becomes a regular column, and a 0, 1, 2, 3 index takes its place
df_reset = df.reset_index()
print("\nAfter reset_index() (Moves index to column):")
display(df_reset)

# 2. Fixing Scrambled Indices after Filtering
# Let's filter the original dataframe for AQI > 90
df_filtered = df_reset[df_reset['aqi'] > 90]
print("\nFiltered Dataset (Notice the scrambled integer index: 0, 2, 3):")
display(df_filtered)

# Using drop=True to renumber the rows cleanly without keeping the scrambled numbers
df_clean_index = df_filtered.reset_index(drop=True)
print("\nAfter reset_index(drop=True) (Cleanly renumbered):")
display(df_clean_index)

Original Dataset (Station is the Index):

           aqi  pm25
station
Howrah     115  48.2
New Town    85  38.1
Salt Lake   92  40.5
Bally      110  45.0

After reset_index() (Moves index to column):

     station  aqi  pm25
0     Howrah  115  48.2
1   New Town   85  38.1
2  Salt Lake   92  40.5
3      Bally  110  45.0

Filtered Dataset (Notice the scrambled integer index: 0, 2, 3):

     station  aqi  pm25
0     Howrah  115  48.2
2  Salt Lake   92  40.5
3      Bally  110  45.0

After reset_index(drop=True) (Cleanly renumbered):

     station  aqi  pm25
0     Howrah  115  48.2
1  Salt Lake   92  40.5
2      Bally  110  45.0

#### **49. What is set_index()?**
The `set_index()` method takes one or more existing columns from your DataFrame and promotes them to become the row labels (the index). This replaces the default sequential integer index (0, 1, 2...) with meaningful identifiers, fundamentally changing how you access your data.

**Key Use Cases and Parameters**  
* **Time-Series Enablement:** Setting a datetime column as the index is mandatory for unlocking Pandas' advanced time-based functions, like resampling hourly data into daily averages.
* **Fast Lookups:** Indexes are heavily optimized for speed. Extracting data using `.loc` on an indexed string (like a station name) is computationally faster than standard boolean filtering.
* **`drop` (Default = `True`):** Automatically removes the promoted column from the main body of the DataFrame. Setting this to `False` keeps the column in the data body while also duplicating it as the index.
* **Hierarchical Indexing:** Passing a list of multiple columns (e.g., `['station', 'date']`) creates a MultiIndex, allowing you to organize complex grouped data in multiple dimensions.

In [49]:
import pandas as pd

# Creating a standard flat dataset
data = {
    'date': ['2026-09-10', '2026-09-11', '2026-09-10', '2026-09-11'],
    'station': ['Howrah', 'Howrah', 'Salt Lake', 'Salt Lake'],
    'aqi': [115, 110, 92, 88]
}
df = pd.DataFrame(data)
print("Original Flat Dataset:")
display(df)

# 1. Setting a Single Column as the Index
# Promotes the 'station' column to the index and removes it from the columns
df_station_idx = df.set_index('station')
print("\nAfter set_index('station'):")
display(df_station_idx)

# Using .loc is now exceptionally clean and fast
print("\nExtracting 'Howrah' data using the new index:")
display(df_station_idx.loc['Howrah'])

# 2. Keeping the Column in the DataFrame
# Promotes 'date' but leaves a copy in the standard columns
df_date_kept = df.set_index('date', drop=False)
print("\nAfter set_index('date', drop=False):")
display(df_date_kept)

# 3. Creating a MultiIndex (Hierarchical Index)
# Nests the dates inside each respective station
df_multi = df.set_index(['station', 'date'])
print("\nAfter set_index(['station', 'date']) (MultiIndex):")
display(df_multi)

Original Flat Dataset:

         date    station  aqi
0  2026-09-10     Howrah  115
1  2026-09-11     Howrah  110
2  2026-09-10  Salt Lake   92
3  2026-09-11  Salt Lake   88

After set_index('station'):

                 date  aqi
station
Howrah     2026-09-10  115
Howrah     2026-09-11  110
Salt Lake  2026-09-10   92
Salt Lake  2026-09-11   88

Extracting 'Howrah' data using the new index:

               date  aqi
station
Howrah   2026-09-10  115
Howrah   2026-09-11  110

After set_index('date', drop=False):

                  date    station  aqi
date
2026-09-10  2026-09-10     Howrah  115
2026-09-11  2026-09-11     Howrah  110
2026-09-10  2026-09-10  Salt Lake   92
2026-09-11  2026-09-11  Salt Lake   88

After set_index(['station', 'date']) (MultiIndex):

                      aqi
station   date
Howrah    2026-09-10  115
          2026-09-11  110
Salt Lake 2026-09-10   92
          2026-09-11   88

#### **50. Why are indexes important?**
The index in Pandas is far more than just a row number—it is the structural backbone of a DataFrame. While you can technically do almost everything without ever touching the index, mastering it unlocks massive performance gains and advanced functionalities.

**The Three Superpowers of the Index**  
* **Lightning-Fast Lookups:** When you filter using boolean masks (e.g., `df[df['station'] == 'Howrah']`), Pandas scans every single row sequentially. If `station` is the index, using `.loc['Howrah']` utilizes hash tables (like a Python dictionary), making data retrieval nearly instantaneous even on datasets with millions of rows.
* **Automatic Data Alignment:** This is the most crucial, yet invisible, feature of Pandas. If you perform mathematical operations between two datasets, Pandas does not match them by row order (Row 1 + Row 1). It matches them purely by their index labels.
* **Time-Series Magic:** In air quality analysis, data is heavily time-dependent. Converting a date column into a `DatetimeIndex` is the mandatory key to unlocking powerful functions like `.resample()` (converting hourly readings to daily averages) or `.rolling()` (calculating 7-day moving averages).

In [50]:
import pandas as pd
import numpy as np

# SUPERPOWER 1: Automatic Data Alignment
# Two series with the exact same stations, but in a completely different order
pm25_morning = pd.Series({'Howrah': 45.1, 'Bally': 38.0, 'Salt Lake': 22.5})
pm25_evening = pd.Series({'Salt Lake': 30.1, 'Howrah': 60.2, 'Bally': 42.0})

# When we add them, Pandas completely ignores the physical order and 
# mathematically aligns them perfectly based on their index labels.
total_daily_pm25 = pm25_morning + pm25_evening
print("Automatic Index Alignment:")
print(total_daily_pm25)

# SUPERPOWER 2: Time-Series Aggregation
# Creating 48 hours of hourly AQI readings
dates = pd.date_range(start='2026-09-10', periods=48, freq='H')
df_time = pd.DataFrame({
    'aqi': np.random.randint(50, 150, size=48)
}, index=dates) # Setting the DatetimeIndex immediately

print("\n\nOriginal Hourly Data (First 3 rows):")
display(df_time.head(3))

# Because the index is datetime, we can instantly "resample" the data.
# Here, we group by Day ('D') and find the maximum AQI for that specific day.
# Doing this without a DatetimeIndex would require complex groupby logic.
daily_max_aqi = df_time.resample('D').max()
print("\nResampled to Daily Maximum AQI:")
display(daily_max_aqi)

Automatic Index Alignment:
Bally         80.0
Howrah       105.3
Salt Lake     52.6
dtype: float64


Original Hourly Data (First 3 rows):

/var/folders/tl/hdrnf2y12_dfs7brk68x42yc0000gn/T/ipykernel_37587/1886231800.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(start='2026-09-10', periods=48, freq='H')

                     aqi
2026-09-10 00:00:00   90
2026-09-10 01:00:00  134
2026-09-10 02:00:00  143

Resampled to Daily Maximum AQI:

            aqi
2026-09-10  147
2026-09-11  146

## Data Manipulation (51–70)

#### **51. What is groupby()?**
The `groupby()` method is the cornerstone of data aggregation in Pandas, operating on the "split-apply-combine" paradigm. It splits your dataset into separate groups based on identical values in a chosen column, applies a calculation to each group independently, and combines the results back into a new summary DataFrame.

**Core Mechanics**  
* **The Grouping Key:** You provide one or more columns to define the groups (e.g., grouping by `station` will create a distinct bucket for every unique station name).
* **Target Selection:** While you can group the entire DataFrame, it is heavily recommended to isolate specific numeric columns *before* applying the math (e.g., `df.groupby('station')['aqi'].mean()` targets only AQI).
* **The Index Shift:** By default, the column you use to group the data is automatically promoted to the index of the resulting DataFrame. Passing `as_index=False` prevents this and keeps the summary as a standard, flat table.
* **Aggregation Functions:** Once grouped, you must apply a function to reduce the grouped rows into a single value. Common functions include `.mean()`, `.sum()`, `.max()`, `.min()`, and `.count()`.

In [51]:
import pandas as pd

# Creating a dataset with multiple readings per station across different zones
data = {
    'station': ['Howrah', 'Bally', 'Howrah', 'Salt Lake', 'Bally', 'Salt Lake'],
    'zone': ['West', 'North', 'West', 'East', 'North', 'East'],
    'aqi': [115, 85, 130, 92, 110, 88],
    'pm25': [48.2, 38.1, 55.0, 40.5, 45.0, 39.2]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Basic Grouping (Single Column, Single Metric)
# Groups by station, selects ONLY the 'aqi' column, and calculates the mean.
# Notice that 'station' becomes the index of the output.
station_avg = df.groupby('station')['aqi'].mean()
print("\nAverage AQI per Station:")
display(station_avg)

# 2. Keeping a Flat DataFrame
# as_index=False keeps 'station' as a standard column.
station_max = df.groupby('station', as_index=False)['aqi'].max()
print("\nMaximum AQI per Station (Flat Table):")
display(station_max)

# 3. Grouping by Multiple Categories (Hierarchical)
# Groups by zone first, then by station within that zone.
# Calculates the mean for all remaining numeric columns (aqi and pm25).
zone_station_avg = df.groupby(['zone', 'station']).mean()
print("\nAverage Metrics per Zone and Station:")
display(zone_station_avg)

Original Dataset:

     station   zone  aqi  pm25
0     Howrah   West  115  48.2
1      Bally  North   85  38.1
2     Howrah   West  130  55.0
3  Salt Lake   East   92  40.5
4      Bally  North  110  45.0
5  Salt Lake   East   88  39.2

Average AQI per Station:

station
Bally         97.5
Howrah       122.5
Salt Lake     90.0
Name: aqi, dtype: float64

Maximum AQI per Station (Flat Table):

     station  aqi
0      Bally  110
1     Howrah  130
2  Salt Lake   92

Average Metrics per Zone and Station:

                   aqi   pm25
zone  station
East  Salt Lake   90.0  39.85
North Bally       97.5  41.55
West  Howrah     122.5  51.60

#### **52. How does groupby() work internally?**
The `groupby()` method operates on a highly optimized structural paradigm known as **Split-Apply-Combine**. Understanding this internal process is crucial because it explains why `groupby()` is incredibly fast and memory-efficient compared to writing manual Python loops.

**The Three Phases of Execution**  
* **The Split (Lazy Evaluation):** When you execute `df.groupby('station')`, Pandas does *not* immediately calculate anything or physically rearrange the data in memory. Instead, it creates a `DataFrameGroupBy` object. Internally, it builds a hash table (dictionary) that maps every unique category to the specific integer row indices where that category exists.
* **The Apply (C-Optimized Execution):** Once you call an aggregation function like `.mean()`, Pandas iterates through that internal dictionary. It grabs the exact rows for each group and passes them to heavily optimized C-based algorithms to calculate the math instantly.
* **The Combine:** Finally, Pandas stitches the individual results back together into a brand new DataFrame, setting your grouping categories as the new index.

In [56]:
import pandas as pd

# Creating a dataset of sensor readings
data = {
    'station': ['Howrah', 'Bally', 'Howrah', 'Salt Lake', 'Bally'],
    'aqi': [115, 85, 130, 92, 110],
    'status': ['Poor', 'Moderate', 'Very Poor', 'Satisfactory', 'Moderate']
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. The Lazy Split
# This does not calculate anything. It just creates the blueprint.
grouped = df.groupby('station')

print("\nThe GroupBy Object Blueprint:")
print(grouped) # Returns a DataFrameGroupBy object in memory

# 2. Peeking Inside the Engine (.groups)
# This reveals the exact dictionary mapping Pandas uses under the hood.
# It links the station name to the integer row index (0, 1, 2, etc.)
print("\nInternal Mapping (Category -> Row Indices):")
for key, indices in grouped.groups.items():
    print(f"Station '{key}' is found at rows: {list(indices)}")

# 3. Interacting with the Split Data (.get_group)
# You can manually extract the exact DataFrame subset for a specific group
# without doing any math, proving the data has been logically split.
howrah_subset = grouped.get_group('Howrah')
print("\nExtracted subset for 'Howrah':")
display(howrah_subset)

# 4. The Apply and Combine
# Only now does Pandas actually do the math and stitch it back together.
final_result = grouped['aqi'].mean()
print("\nFinal Combined Result:")
print(final_result)

Original Dataset:

     station  aqi        status
0     Howrah  115          Poor
1      Bally   85      Moderate
2     Howrah  130     Very Poor
3  Salt Lake   92  Satisfactory
4      Bally  110      Moderate

The GroupBy Object Blueprint:
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x134315a90>

Internal Mapping (Category -> Row Indices):
Station 'Bally' is found at rows: [1, 4]
Station 'Howrah' is found at rows: [0, 2]
Station 'Salt Lake' is found at rows: [3]

Extracted subset for 'Howrah':

  station  aqi     status
0  Howrah  115       Poor
2  Howrah  130  Very Poor

Final Combined Result:
station
Bally         97.5
Howrah       122.5
Salt Lake     92.0
Name: aqi, dtype: float64

#### **53. Difference between aggregation and transformation?**
The fundamental difference lies in the shape of the output. **Aggregation** reduces a group of rows into a single summary value, while **transformation** performs a group-level calculation but returns a result for every single original row, perfectly preserving the dataset's exact length and index.

| Feature | Aggregation (`agg`) | Transformation (`transform`) |
| --- | --- | --- |
| **Output Shape** | Reduced (one row per group). | Identical to the original dataset (one row per original row). |
| **Primary Purpose** | Summarizing data to understand macroscopic trends (e.g., "What is the overall average AQI for each station?"). | Broadcasting group metrics back to individual rows (e.g., "How far does *this specific reading* deviate from its station's historical average?"). |
| **Resulting Index** | The grouping categories become the new index (unless `as_index=False`). | Retains the exact original index of the DataFrame. |

In [57]:
import pandas as pd

# Creating a dataset with multiple daily readings per station
data = {
    'date': ['2026-09-10', '2026-09-11', '2026-09-12', '2026-09-10', '2026-09-11', '2026-09-12'],
    'station': ['Howrah', 'Howrah', 'Howrah', 'Salt Lake', 'Salt Lake', 'Salt Lake'],
    'aqi': [115, 130, 100, 92, 85, 95]
}
df = pd.DataFrame(data)
print("Original Dataset (6 rows):")
display(df)

# 1. Aggregation (The Shrink)
# Reduces the 6 rows into 2 summary rows (one for each station).
station_means = df.groupby('station')['aqi'].mean()
print("\nAggregation Output (Reduced to 2 rows):")
print(station_means)

# 2. Transformation (The Broadcast)
# Calculates the same station means, but broadcasts that mean back to every 
# original row belonging to that station. Returns exactly 6 rows.
df['station_average'] = df.groupby('station')['aqi'].transform('mean')

# 3. Practical Use Case of Transform: Calculating Deviation
# Because the shape is preserved, we can subtract the transformed column 
# from the original column mathematically in the same DataFrame.
df['aqi_deviation'] = df['aqi'] - df['station_average']

print("\nTransformation Output (Original 6 rows preserved with new metrics):")
display(df)

Original Dataset (6 rows):

         date    station  aqi
0  2026-09-10     Howrah  115
1  2026-09-11     Howrah  130
2  2026-09-12     Howrah  100
3  2026-09-10  Salt Lake   92
4  2026-09-11  Salt Lake   85
5  2026-09-12  Salt Lake   95

Aggregation Output (Reduced to 2 rows):
station
Howrah       115.000000
Salt Lake     90.666667
Name: aqi, dtype: float64

Transformation Output (Original 6 rows preserved with new metrics):

         date    station  aqi  station_average  aqi_deviation
0  2026-09-10     Howrah  115       115.000000       0.000000
1  2026-09-11     Howrah  130       115.000000      15.000000
2  2026-09-12     Howrah  100       115.000000     -15.000000
3  2026-09-10  Salt Lake   92        90.666667       1.333333
4  2026-09-11  Salt Lake   85        90.666667      -5.666667
5  2026-09-12  Salt Lake   95        90.666667       4.333333

#### **54. What are aggregation functions?**
Aggregation functions are mathematical operations that take a collection of data points—such as an entire column or a specific group—and compress them into a single summary value. They are the engine behind data summarization, answering questions like "What is the maximum?", "What is the average?", or "How many exist?"

**Common Pandas Aggregation Functions**  
| Function | What it Calculates | Best For |
| --- | --- | --- |
| **`mean()` / `median()**` | The average or the middle value. | Finding typical pollution baselines. |
| **`max()` / `min()**` | The absolute highest or lowest value. | Identifying peak toxicity events or sensor floor limits. |
| **`sum()`** | The total added value of all points. | Calculating total cumulative emissions over time. |
| **`count()`** | The total number of *non-null* (valid) entries. | Auditing sensor uptime and data completeness. |
| **`std()` / `var()**` | Standard deviation and variance. | Measuring how wildly readings fluctuate (volatility). |

While you can apply these directly to a column (e.g., `df['aqi'].mean()`), their true power is unlocked when combined with the `.agg()` method, which allows you to run multiple different calculations simultaneously.

In [58]:
import pandas as pd

# Creating a dataset of daily sensor readings across two stations
data = {
    'station': ['Howrah', 'Howrah', 'Howrah', 'Salt Lake', 'Salt Lake', 'Salt Lake'],
    'date': ['2026-09-10', '2026-09-11', '2026-09-12', '2026-09-10', '2026-09-11', '2026-09-12'],
    'aqi': [115, 130, 90, 92, 85, 95],
    'pm25': [48.2, 55.0, 35.1, 40.5, 38.1, 42.0]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. Global Aggregation using .agg()
# Calculates multiple statistics for the entire DataFrame at once.
global_stats = df[['aqi', 'pm25']].agg(['mean', 'max', 'min'])
print("\nGlobal Statistics (Entire Dataset):")
display(global_stats)

# 2. Advanced GroupBy Aggregation (The Gold Standard)
# Passing a dictionary to .agg() allows you to specify exactly which 
# calculations should be applied to which specific columns.
station_summary = df.groupby('station').agg({
    'aqi': ['mean', 'max'],    # Calculate both average and peak AQI
    'pm25': 'min',             # Calculate only the lowest PM2.5
    'date': 'count'            # Use 'date' to count total valid readings
})

print("\nTargeted Statistics per Station:")
display(station_summary)

# 3. Flattening the MultiIndex Columns
# .agg() often creates stacked (MultiIndex) column names like ('aqi', 'mean').
# This list comprehension flattens them into clean strings like 'aqi_mean'.
station_summary.columns = [f"{col[0]}_{col[1]}" for col in station_summary.columns]
print("\nAfter Flattening the Column Names:")
display(station_summary.reset_index())

Original Dataset:

     station        date  aqi  pm25
0     Howrah  2026-09-10  115  48.2
1     Howrah  2026-09-11  130  55.0
2     Howrah  2026-09-12   90  35.1
3  Salt Lake  2026-09-10   92  40.5
4  Salt Lake  2026-09-11   85  38.1
5  Salt Lake  2026-09-12   95  42.0

Global Statistics (Entire Dataset):

             aqi   pm25
mean  101.166667  43.15
max   130.000000  55.00
min    85.000000  35.10

Targeted Statistics per Station:

                  aqi       pm25  date
                 mean  max   min count
station
Howrah     111.666667  130  35.1     3
Salt Lake   90.666667   95  38.1     3

After Flattening the Column Names:

     station    aqi_mean  aqi_max  pm25_min  date_count
0     Howrah  111.666667      130      35.1           3
1  Salt Lake   90.666667       95      38.1           3

#### **55. How do you calculate multiple aggregations?**
The `.agg()` method is the dedicated tool for calculating multiple statistics simultaneously. While you can pass a list or dictionary to this method, the most robust technique for modern Pandas is using **Named Aggregations**, which calculates the statistics and names the new columns cleanly in a single step.

**Key Syntax Methods**  
* **The List Approach (`agg(['mean', 'max'])`):** Applies every function in the list to every numeric column. This is fast but often calculates more than you actually need.
* **The Dictionary Approach (`agg({'aqi': 'mean', 'pm25': 'max'})`):** Maps specific functions to specific columns. However, if you calculate multiple stats for one column (e.g., `{'aqi': ['mean', 'max']}`), it creates a cumbersome MultiIndex column structure.
* **Named Aggregations (`agg(new_name=('col', 'func'))`):** The gold standard. You define the exact name of the output column, the source column it reads from, and the mathematical function applied. It completely prevents messy MultiIndex columns.

In [59]:
import pandas as pd

# Creating a dataset of sensor readings across different zones
data = {
    'station': ['Howrah', 'Bally', 'Howrah', 'Salt Lake', 'Bally', 'Salt Lake'],
    'aqi': [115, 85, 130, 92, 110, 88],
    'pm25': [48.2, 38.1, 55.0, 40.5, 45.0, 39.2]
}
df = pd.DataFrame(data)
print("Original Dataset:")
display(df)

# 1. The List Approach (Applying the same stats to multiple columns)
# Calculates mean, min, and max for BOTH aqi and pm25 simultaneously.
list_agg = df.groupby('station')[['aqi', 'pm25']].agg(['mean', 'max', 'min'])
print("\nList Aggregation (Notice the nested MultiIndex columns):")
display(list_agg)

# 2. The Dictionary Approach (Targeted statistics)
# Calculates different stats for different columns.
dict_agg = df.groupby('station').agg({
    'aqi': ['min', 'max'],
    'pm25': 'mean'
})
print("\nDictionary Aggregation (Still creates MultiIndex columns):")
display(dict_agg)

# 3. Named Aggregations (The Best Practice)
# Syntax: new_column_name = ('source_column', 'function_name')
# This returns a perfectly flat, beautifully named DataFrame immediately.
named_agg = df.groupby('station').agg(
    avg_aqi=('aqi', 'mean'),
    peak_aqi=('aqi', 'max'),
    baseline_pm25=('pm25', 'min'),
    reading_count=('aqi', 'count')
).reset_index()

print("\nNamed Aggregation (Clean, flat columns ready for analysis):")
display(named_agg)

Original Dataset:

     station  aqi  pm25
0     Howrah  115  48.2
1      Bally   85  38.1
2     Howrah  130  55.0
3  Salt Lake   92  40.5
4      Bally  110  45.0
5  Salt Lake   88  39.2

List Aggregation (Notice the nested MultiIndex columns):

             aqi             pm25
            mean  max  min   mean   max   min
station
Bally       97.5  110   85  41.55  45.0  38.1
Howrah     122.5  130  115  51.60  55.0  48.2
Salt Lake   90.0   92   88  39.85  40.5  39.2

Dictionary Aggregation (Still creates MultiIndex columns):

           aqi        pm25
           min  max   mean
station
Bally       85  110  41.55
Howrah     115  130  51.60
Salt Lake   88   92  39.85

Named Aggregation (Clean, flat columns ready for analysis):

     station  avg_aqi  peak_aqi  baseline_pm25  reading_count
0      Bally     97.5       110           38.1              2
1     Howrah    122.5       130           48.2              2
2  Salt Lake     90.0        92           39.2              2

#### **56. What is pivot_table()?**

#### **57. Difference between pivot() and pivot_table()?**

#### **58. What is melting?**

#### **59. What is melt()?**

#### **60. What is stack()?**

#### **61. What is unstack()?**

#### **62. Difference between long and wide data?**

#### **63. What is explode()?**

#### **64. What is crosstab()?**

#### **65. What is cut()?**

#### **66. What is qcut()?**

#### **67. How do you bin continuous data?**

#### **68. What is transform()?**

#### **69. Difference between transform() and aggregate()?**

#### **70. What is pipe()?**

## Merge, Join & Combine (71–85)

#### **71. Difference between merge(), join(), and concat()?**

#### **72. Explain different types of joins.**

#### **73. What is an inner join?**

#### **74. What is a left join?**

#### **75. What is a right join?**

#### **76. What is a full outer join?**

#### **77. What happens when merge keys have duplicates?**

#### **78. How do you merge on multiple columns?**

#### **79. How do you concatenate DataFrames vertically?**

#### **80. How do you concatenate horizontally?**

#### **81. What is hierarchical indexing?**

#### **82. What is a MultiIndex?**

#### **83. How do you flatten a MultiIndex?**

#### **84. What is combine_first()?**

#### **85. How do you compare two DataFrames?**

## Advanced Level (86–100)

#### **86. How is a DataFrame stored in memory?**

#### **87. Why is Pandas slower than NumPy for numerical operations?**

#### **88. What is vectorization in Pandas?**

#### **89. When should you avoid using apply()?**

#### **90. How can you optimize large DataFrames?**

#### **91. What are categorical data types, and when should you use them?**

#### **92. How do you reduce memory usage in a DataFrame?**

#### **93. What are time series in Pandas?**

#### **94. How do you work with datetime columns?**

#### **95. What is resampling?**

#### **96. What is rolling window analysis?**

#### **97. How do you handle time zones in Pandas?**

#### **98. How would you process a 10 GB CSV that doesn't fit into memory?**

#### **99. What are common performance bottlenecks in Pandas, and how can you address them?**

#### **100. In what situations would you choose Pandas over NumPy, and when would you choose NumPy instead?**

## Frequently Asked Scenario-Based Questions

#### **101. How would you clean a messy dataset before analysis?**

#### **102. How do you identify and remove duplicate records?**

#### **103. How would you fill missing values differently for numerical and categorical columns?**

#### **104. How do you detect and handle outliers using Pandas?**

#### **105. How would you find the top 5 customers by total sales?**

#### **106. How would you calculate month-over-month growth from a sales dataset?**

#### **107. How do you combine data from multiple CSV files into one DataFrame?**

#### **108. How would you reshape a dataset from wide format to long format?**

#### **109. How do you optimize a slow Pandas script processing millions of rows?**

#### **110. What are the most common mistakes developers make when working with Pandas?**